'use client';
import { lazy, Suspense, useEffect, useState } from 'react';
import { toast } from 'sonner';
import { Plus, Upload, KeyRound, Save, Users, Mail, Check, LoaderCircle, Pencil } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from '@/components/ui/table';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Choice } from './choice';
import { AgentPortfolio } from './agent-portfolio';
import { ManagerAccess } from './manager-access';
import { StockImport } from './stock-import';
import { api, errorMessage, normalize } from '@/lib/client-api';
import { readClients, type ImportClient } from '@/lib/import-clients';
import type { User, Warehouse, Settings, OperationalMailSettings, ManagerMailSettings, ImportStatus, ImportStatusItem } from '@/lib/types';

const SalesImport = lazy(() => import('./sales').then(module => ({ default: module.SalesImport })));

function importStatusText(label:string,item:ImportStatusItem|null,ready:boolean,unavailable:boolean) {
  if(unavailable)return `${label}: nu a putut fi verificat momentan.`;
  if(!ready)return `${label}: se verifică…`;
  if(!item)return `${label}: nu există încă.`;
  const when=new Date(item.importedAt).toLocaleString('ro-RO',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});
  const details=[item.filename,when,item.month?`luna ${item.month}`:'',item.rows?`${item.rows.toLocaleString('ro-RO')} rânduri`:'',item.warehouses?`${item.warehouses} gestiuni`:''].filter(Boolean);
  return `${label}: ${details.join(' · ')}`;
}

function ManagerImports() {
  const [status,setStatus]=useState<ImportStatus>({sales:null,stock:null}),[ready,setReady]=useState(false),[unavailable,setUnavailable]=useState(false);
  useEffect(()=>{let active=true;const refresh=async()=>{try{const next=await api<ImportStatus>('admin/imports/status');if(active){setStatus(next);setUnavailable(false);setReady(true);}}catch{if(active){setUnavailable(true);setReady(true);}}};const onImport=()=>void refresh();void refresh();window.addEventListener('sales-imported',onImport);window.addEventListener('stock-imported',onImport);return()=>{active=false;window.removeEventListener('sales-imported',onImport);window.removeEventListener('stock-imported',onImport);};},[]);
  return <div className="settings-imports"><Suspense fallback={<div className="sales-loading">Se încarcă importul de vânzări…</div>}><SalesImport lastImportText={importStatusText('Ultimul import vânzări',status.sales,ready,unavailable)}/></Suspense><StockImport lastImportText={importStatusText('Ultimul import stoc',status.stock,ready,unavailable)}/></div>;
}

export function Team({users,warehouses,onUsers,warnings,canCreateAgents}:{users:User[];warehouses:Warehouse[];onUsers:(u:User[])=>void;warnings:{row:number;name:string;reason:string}[];canCreateAgents:boolean}) {
  const [portfolioAgent,setPortfolioAgent]=useState<User|null>(null);
  const [dialog,setDialog]=useState<'new'|'import'|'reset'|null>(null),[target,setTarget]=useState<User|null>(null),[warehouse,setWarehouse]=useState('g-5'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState('');
  const [preview,setPreview]=useState<{clients:ImportClient[];warnings:string[];sheet:string}|null>(null),[filename,setFilename]=useState('');
  async function action(body:unknown) {setBusy(true);setError('');try{const r=await api<{users:User[]}>('admin/users','POST',body);onUsers(r.users);setDialog(null);toast.success('Contul a fost actualizat.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function importFile(file?:File) {if(!file)return;setBusy(true);setError('');setPreview(null);setFilename(file.name);try{setPreview(await readClients(file));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function commitImport() {if(!preview)return;setBusy(true);setError('');try{const r=await api<{count:number;users:User[]}>('admin/import-clients','POST',{warehouseId:warehouse,clients:preview.clients});onUsers(r.users);setDialog(null);setPreview(null);toast.success(`${r.count} clienți importați.`);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  const filtered=users.filter(u=>u.role==='agent'&&normalize(u.name+' '+u.username+' '+u.warehouseName+' '+u.siteCode).includes(normalize(query)));
  if(portfolioAgent) return <AgentPortfolio key={portfolioAgent.id} agent={users.find(u=>u.id===portfolioAgent.id)||portfolioAgent} users={users} onUsers={onUsers} onBack={()=>setPortfolioAgent(null)} canEditSiteCode={canCreateAgents}/>;
  return <><div className="page-heading"><div><span className="eyebrow">ADMINISTRARE</span><h1>Echipă</h1><p>Conturi, gestiuni și portofoliul fiecărui agent.</p></div>{canCreateAgents&&<button className="primary" onClick={()=>{setDialog('new');setError('');}}><Plus size={19}/> Agent nou</button>}</div>
    {!dialog&&error&&<p className="error-banner" role="alert">{error}</p>}
    <div className="team-admin-stack">{canCreateAgents&&<ManagerAccess users={users} onUsers={onUsers}/>}<section className="panel"><div className="panel-toolbar"><div className="search-box"><Users size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Caută agent sau gestiune…" aria-label="Caută agent"/></div><button className="secondary" onClick={()=>{setDialog('import');setError('');setPreview(null);}}><Upload size={17}/> Importă portofoliu Excel</button></div>
    <Table className="orders-table team-table"><TableHeader><TableRow><TableHead>AGENȚI</TableHead><TableHead>GESTIUNE</TableHead><TableHead>SITECODE</TableHead><TableHead>CLIENȚI</TableHead><TableHead>STATUS</TableHead><TableHead>CONT</TableHead></TableRow></TableHeader><TableBody>{filtered.map(u=><TableRow key={u.id}><TableCell><div className="person"><span className="avatar small">{u.name.split(' ').slice(0,2).map(s=>s[0]).join('')}</span><span>{u.role==='agent'?<button className="portfolio-name" onClick={()=>setPortfolioAgent(u)} title="Vezi magazinele agentului">{u.name}</button>:<strong>{u.name}</strong>}<small>{u.username} · {u.role==='manager'?'Manager':'Agent'}</small></span></div></TableCell><TableCell><span className="cell-name">{u.warehouseName||'Toate gestiunile'}</span></TableCell><TableCell>{u.siteCode||'—'}</TableCell><TableCell><strong>{u.role==='manager'?'—':u.clientCount||0}</strong></TableCell><TableCell><span className={'badge '+(u.active?'finalized':'draft')}>{u.active?'Activ':'Dezactivat'}</span></TableCell><TableCell><div className="table-actions">{u.role==='agent'&&<><button className="icon-button" aria-label={`Resetează parola ${u.name}`} title="Resetează parola" onClick={()=>{setTarget(u);setDialog('reset');setError('');}}><KeyRound size={18}/></button><button className="quiet" disabled={busy} onClick={()=>void action({action:'toggle',id:u.id,version:u.profileVersion})}>{u.active?'Dezactivează':'Activează'}</button></>}</div></TableCell></TableRow>)}</TableBody></Table></section>
    {warnings.length>0&&<details className="source-warnings"><summary>{warnings.length} rânduri din portofoliul inițial au date incomplete</summary><p>Completează datele în Excel înainte de a reimporta portofoliul.</p><ul>{warnings.map(w=><li key={w.row}>Rând {w.row}: {w.name} — {w.reason}.</li>)}</ul></details>}
    </div>
    <Dialog open={!!dialog} onOpenChange={open=>{if(!open&&!busy)setDialog(null);}}><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>{dialog==='new'?'Adaugă agent':dialog==='reset'?'Resetează parola':'Importă portofoliul de clienți'}</DialogTitle><DialogDescription>{dialog==='import'?'Selectează gestiunea și verifică datele înainte de import.':dialog==='reset'?target?.name:'Parola este setată de manager și devine activă imediat.'}</DialogDescription></DialogHeader>
      {error&&<p className="error-banner" role="alert">{error}</p>}
      {dialog==='new'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void action({...data,warehouseId:warehouse});}}><label>Numele agentului<input name="name" required maxLength={100}/></label><label>Utilizator<input name="username" required minLength={3} pattern={'[a-zA-Z0-9._\\-]+'} autoCapitalize="none" autoComplete="off"/></label><label htmlFor="new-warehouse">Gestiune<Choice id="new-warehouse" label="Gestiunea agentului" value={warehouse} onChange={setWarehouse} options={warehouses.map(g=>({value:g.id,label:g.name}))}/></label><label>Parolă<input name="password" type="password" autoComplete="new-password" required minLength={10} maxLength={128}/></label><button className="primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Plus size={18}/>} Creează contul</button></form>}
      {dialog==='reset'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void action({action:'reset',id:target?.id,version:target?.profileVersion,password:new FormData(e.currentTarget).get('password')});}}><label>Noua parolă<input name="password" type="password" autoComplete="new-password" required minLength={10} maxLength={128}/></label><p className="muted">Agentul va fi deconectat de pe dispozitive. Parola devine activă imediat și nu poate fi schimbată de agent.</p><button className="primary" disabled={busy}><KeyRound size={18}/> Salvează parola</button></form>}
      {dialog==='import'&&<div className="form-stack"><label htmlFor="import-warehouse">Gestiune<Choice id="import-warehouse" label="Gestiune pentru import" value={warehouse} onChange={setWarehouse} options={warehouses.map(g=>({value:g.id,label:g.name}))}/></label><label className="file-drop"><Upload size={25}/><strong>Alege fișierul Excel</strong><small>.xlsx · maximum 8 MB</small><input type="file" accept=".xlsx" disabled={busy} onChange={e=>void importFile(e.target.files?.[0])}/></label>{filename&&<p className="muted">{filename}</p>}
        {preview&&<><div className="import-summary"><Check size={19}/><b>{preview.clients.length} clienți</b><span>Foaia „{preview.sheet}”</span></div><div className="import-sample">{preview.clients.slice(0,4).map((c,i)=><p key={i}><b>{c.name}</b><small>CUI {c.cui} · {c.city}</small></p>)}</div>{preview.warnings.length>0&&<details><summary>{preview.warnings.length} rânduri incomplete vor fi omise</summary><ul>{preview.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}<p className="notice">Importul înlocuiește portofoliul activ al gestiunii selectate. Avizele deja salvate își păstrează datele clientului.</p><button className="primary" disabled={busy} onClick={()=>void commitImport()}>{busy?<LoaderCircle size={18} className="spin"/>:<Upload size={18}/>} Importă {preview.clients.length} clienți</button></>}
      </div>}
    </DialogContent></Dialog>
  </>;
}

export function SettingsPanel({settings,users,onSettings,onUsers}:{settings:Settings;users:User[];onSettings:(s:Settings)=>void;onUsers:(u:User[])=>void}) {
  const [values,setValues]=useState(settings),[busy,setBusy]=useState(false),[error,setError]=useState(''),[settingsTab,setSettingsTab]=useState('email'),[accountAgent,setAccountAgent]=useState<User|null>(null),[accountBusy,setAccountBusy]=useState(false),[accountError,setAccountError]=useState('');
  async function save(e:React.SyntheticEvent) {e.preventDefault();setBusy(true);setError('');try{const r=await api<{settings:Settings}>('admin/settings','PUT',values);onSettings(r.settings);setValues(r.settings);toast.success('Setările au fost salvate.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function saveAccount(e:React.SyntheticEvent<HTMLFormElement>) {e.preventDefault();if(!accountAgent||accountBusy)return;const data=Object.fromEntries(new FormData(e.currentTarget));if(data.password!==data.confirm){setAccountError('Cele două parole nu coincid.');return;}setAccountBusy(true);setAccountError('');try{const r=await api<{users:User[]}>('admin/users/'+accountAgent.id,'PUT',{version:accountAgent.profileVersion,username:data.username,password:data.password});onUsers(r.users);setAccountAgent(null);toast.success('Datele de acces ale agentului au fost salvate.');}catch(e){setAccountError(errorMessage(e));}finally{setAccountBusy(false);}}
  const orderGroups=([
    ['accessoriesEmail','accessoriesCc','Comenzi accesorii',4],
    ['standsEmail','standsCc','Comenzi standuri',4],
    ['simEmail','simCc','Avize client SIM 0',2],
  ] as const);
  return <><div className="page-heading"><div><span className="eyebrow">ADMINISTRARE</span><h1>Setări comenzi</h1><p>Destinatarii mesajelor, frecvența comenzilor și accesul agenților.</p></div></div><div className="settings-form panel"><Tabs value={settingsTab} onValueChange={setSettingsTab}><TabsList className="settings-tabs" variant="line"><TabsTrigger value="email"><Mail size={17}/> E-mail și comenzi</TabsTrigger><TabsTrigger value="accounts"><KeyRound size={17}/> Conturi agenți</TabsTrigger><TabsTrigger value="sales-import"><Upload size={17}/> Importuri</TabsTrigger></TabsList><TabsContent value="email"><form className="form-stack" onSubmit={e=>void save(e)}><div className="section-heading"><Mail size={22}/><div><h2>Adrese de e-mail</h2><p>Vor fi incluse în mesajele pregătite pentru agenți.</p></div></div>
    {orderGroups.map(([key,ccKey,label,count])=><fieldset className="email-recipient-group" key={key}><legend>{label}</legend><label className="email-to">To — Către<input type="email" value={values[key]} maxLength={254} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))} placeholder="Destinatar principal"/></label><div className="email-cc-grid">{Array.from({length:count},(_,index)=><label key={index}>CC {index+1}<input type="email" value={values[ccKey]?.[index]||''} maxLength={254} onChange={e=>setValues(v=>({...v,[ccKey]:Array.from({length:count},(_,position)=>position===index?e.target.value:v[ccKey]?.[position]||'')}))} placeholder="Adresă în copie (opțional)"/></label>)}</div></fieldset>)}
    <fieldset className="email-recipient-group"><legend>Partener nou</legend><div className="email-cc-grid">{Array.from({length:2},(_,index)=><label key={index}>To {index+1}<input type="email" value={values.partnerTo?.[index]||''} maxLength={254} onChange={e=>setValues(v=>({...v,partnerTo:Array.from({length:2},(_,position)=>position===index?e.target.value:v.partnerTo?.[position]||'')}))} placeholder={index===0?'Destinatar principal':'Al doilea destinatar (opțional)'}/></label>)}</div><div className="email-cc-grid"><label>CC 1<input type="email" value={values.partnerCc?.[0]||''} maxLength={254} onChange={e=>setValues(v=>({...v,partnerCc:[e.target.value]}))} placeholder="Adresă în copie (opțional)"/></label></div></fieldset>
    <div className="settings-divider"/><label>Comenzi accesorii / agent / săptămână<input type="number" min={1} max={7} value={values.weeklyLimit} onChange={e=>setValues(v=>({...v,weeklyLimit:Number(e.target.value)}))} required/></label><p className="muted">Implicit: maximum două comenzi finalizate, de luni până duminică, ora României. Ciornele, standurile și avizele SIM nu consumă această limită.</p>{error&&<p className="error-banner" role="alert">{error}</p>}<button className="primary" disabled={busy}><Save size={18}/> Salvează setările</button></form></TabsContent><TabsContent value="accounts"><div className="section-heading"><KeyRound size={22}/><div><h2>Conturi agenți</h2><p>Schimbă utilizatorul și parola pentru fiecare agent.</p></div></div><div className="agent-account-list">{users.filter(u=>u.role==='agent').map(u=><div className="agent-account-row" key={u.id}><div><strong>{u.name}</strong><small>{u.username} · {u.warehouseName}</small></div><button type="button" className="secondary" onClick={()=>{setAccountAgent(u);setAccountError('');}}><Pencil size={16}/> Editează accesul</button></div>)}</div></TabsContent><TabsContent value="sales-import"><ManagerImports/></TabsContent></Tabs></div><Dialog open={!!accountAgent} onOpenChange={open=>{if(!open&&!accountBusy)setAccountAgent(null);}}><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Editează datele de acces</DialogTitle><DialogDescription>{accountAgent?.name} · {accountAgent?.warehouseName}</DialogDescription></DialogHeader><form className="form-stack" onSubmit={e=>void saveAccount(e)}><label>Utilizator<input name="username" defaultValue={accountAgent?.username} required minLength={3} maxLength={80} pattern={'[a-zA-Z0-9._\\-]+'} autoCapitalize="none" autoComplete="off"/></label><label>Parolă nouă<input name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/></label><label>Confirmă parola<input name="confirm" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/></label>{accountError&&<p className="error-banner" role="alert">{accountError}</p>}<p className="muted">Parola este activă imediat și poate fi schimbată ulterior doar de manager.</p><button className="primary" disabled={accountBusy}>{accountBusy?<LoaderCircle className="spin" size={18}/>:<KeyRound size={18}/>} Salvează datele de acces</button></form></DialogContent></Dialog></>;
}

export function ManagerMailPanel({settings,regionalSettings,mixed,onSettings,onRegionalSettings}:{settings:ManagerMailSettings;regionalSettings:OperationalMailSettings;mixed:boolean;onSettings:(s:ManagerMailSettings)=>void;onRegionalSettings:(s:OperationalMailSettings)=>void}) {
  const [values,setValues]=useState(settings),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [routing,setRouting]=useState(regionalSettings),[routingBusy,setRoutingBusy]=useState(false),[routingError,setRoutingError]=useState('');
  async function save(e:React.SyntheticEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<{managerMailSettings:ManagerMailSettings}>('admin/manager-mail','PUT',values);onSettings(r.managerMailSettings);setValues(r.managerMailSettings);toast.success('Adresele tale au fost salvate.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function saveRouting(e:React.SyntheticEvent){e.preventDefault();setRoutingBusy(true);setRoutingError('');try{const r=await api<{regionalSettings:OperationalMailSettings}>('admin/regional-settings','PUT',routing);onRegionalSettings(r.regionalSettings);setRouting(r.regionalSettings);toast.success('Destinatarii regiunii au fost salvați.');}catch(e){setRoutingError(errorMessage(e));}finally{setRoutingBusy(false);}}
  const orderGroups=([
    ['accessoriesEmail','accessoriesCc','Comenzi accesorii',4],
    ['standsEmail','standsCc','Comenzi standuri, cartele & telefoane',4],
    ['simEmail','simCc','Avize client SIM 0',2],
  ] as const);
  return <><div className="page-heading"><div><span className="eyebrow">SETĂRI MANAGER</span><h1>Setări manager</h1><p>Configurează destinatarii regiunii, adresele tale și importurile operaționale.</p></div></div><div className="settings-form panel"><Tabs defaultValue="email"><TabsList className="settings-tabs" variant="line"><TabsTrigger value="email"><Mail size={17}/> E-mail</TabsTrigger><TabsTrigger value="imports"><Upload size={17}/> Importuri</TabsTrigger></TabsList><TabsContent value="email"><div className="form-stack">
    <form className="form-stack" onSubmit={e=>void saveRouting(e)}>
      <div className="section-heading"><Mail size={22}/><div><h2>Destinatari regiune</h2><p>Se aplică tuturor agenților din aria ta. Managerii care împart aceeași echipă editează aceleași adrese.</p></div></div>
      {mixed&&<p className="notice">Agenții din aria ta au momentan configurații diferite. Salvarea va aplica aceleași adrese întregii arii pe care o administrezi.</p>}
      {orderGroups.map(([key,ccKey,label,count])=><fieldset className="email-recipient-group" key={key}><legend>{label}</legend><label className="email-to">To — Către<input type="email" value={routing[key]} maxLength={254} onChange={e=>setRouting(v=>({...v,[key]:e.target.value}))} placeholder="Destinatar principal"/></label><div className="email-cc-grid">{Array.from({length:count},(_,index)=><label key={index}>CC {index+1}<input type="email" value={routing[ccKey]?.[index]||''} maxLength={254} onChange={e=>setRouting(v=>({...v,[ccKey]:Array.from({length:count},(_,position)=>position===index?e.target.value:v[ccKey]?.[position]||'')}))} placeholder="Adresă în copie (opțional)"/></label>)}</div></fieldset>)}
      <fieldset className="email-recipient-group"><legend>Partener nou</legend><div className="email-cc-grid">{Array.from({length:2},(_,index)=><label key={index}>To {index+1}<input type="email" value={routing.partnerTo?.[index]||''} maxLength={254} onChange={e=>setRouting(v=>({...v,partnerTo:Array.from({length:2},(_,position)=>position===index?e.target.value:v.partnerTo?.[position]||'')}))} placeholder={index===0?'Destinatar principal':'Al doilea destinatar (opțional)'}/></label>)}</div><div className="email-cc-grid"><label>CC 1<input type="email" value={routing.partnerCc?.[0]||''} maxLength={254} onChange={e=>setRouting(v=>({...v,partnerCc:[e.target.value]}))} placeholder="Adresă în copie (opțional)"/></label></div></fieldset>
      <p className="muted">Adresele managerilor regionali activi alocați agentului se adaugă automat separat. Nu este nevoie să le copiezi aici.</p>
      {routingError&&<p className="error-banner" role="alert">{routingError}</p>}<button className="primary" disabled={routingBusy}><Save size={18}/>{routingBusy?'Se salvează…':'Salvează destinatarii regiunii'}</button>
    </form>
    <div className="settings-divider"/>
    <form className="form-stack" onSubmit={e=>void save(e)}><div className="section-heading"><Mail size={22}/><div><h2>Adresele mele</h2><p>Aceste adrese sunt adăugate automat la mesajele agenților pe care îi administrezi.</p></div></div>{([['accessories','Comenzi accesorii'],['stands','Comenzi standuri, cartele & telefoane'],['sim','Avize client SIM 0'],['partner','Partener nou']] as const).map(([key,label])=><label key={key}>{label}<input type="email" value={values[key]} maxLength={254} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))} placeholder="name@example.invalid"/></label>)}<p className="muted">Dacă doi manageri administrează aceeași echipă, ambele adrese personale sunt adăugate automat; destinatarii regiunii rămân comuni.</p>{error&&<p className="error-banner" role="alert">{error}</p>}<button className="primary" disabled={busy}><Save size={18}/>{busy?'Se salvează…':'Salvează adresele mele'}</button></form>
  </div></TabsContent><TabsContent value="imports"><div className="section-heading"><Upload size={22}/><div><h2>Importuri operaționale</h2><p>Vânzările și stocurile sunt surse comune. Dacă alt manager a încărcat deja același fișier, aplicația te anunță și nu îl dublează.</p></div></div><ManagerImports/></TabsContent></Tabs></div></>
}
