'use client';
import {lazy,Suspense,useEffect,useState} from 'react';
import {api,errorMessage,money} from '@/lib/client-api';
import {bucharestReportingMonthKey} from '@/lib/bucharest-month';
import {clientFilters,type ClientFilter,type ClientSalesResult,type ClientSalesRow,type ClientSort} from '@/lib/client-sales-types';
import './client-sales.css';
const PartnerSheet=lazy(()=>import('./partner-portfolio').then(m=>({default:m.PartnerSheet})));
const amount=(value:number|null)=>value===null?'—':money(value/100);
const number=(value:number|null)=>value===null?'—':value.toLocaleString('ro-RO',{maximumFractionDigits:2});
const date=(value:string|null)=>value?value.split('-').reverse().join('.'):'—';
const labels:Record<ClientFilter,string>={all:'Toți',billed:'Facturați',unbilled:'Fără facturare',absentPrevious:'Absenți față de luna trecută',absentThree:'Absenți față de 3 luni',new:'Prima facturare recentă',repeat:'Noi cu repetare',waiting:'Noi în așteptare',overdue:'Noi de verificat',reactivated:'Reactivați',visited:'Cu vizită înregistrată',unvisited:'Fără vizită înregistrată',unvisitedPrevious:'Vizitați luna trecută, nu și acum',unvisitedThree:'Vizitați în ultimele 3 luni, nu și acum',unknown:'Istoric necunoscut / parțial'};
const status=(r:ClientSalesRow)=>!r.linked?'Neasociat':!r.identityComplete||r.metrics.missingValues?'Istoric parțial':r.health.status==='overdue'?'Repetare de verificat':r.health.status==='waiting'?'În așteptarea repetării':r.flags.includes('repeat')?'Nou cu repetare':r.flags.includes('new')?'Prima facturare recentă':r.flags.includes('reactivated')?'Reactivat':r.flags.includes('absentPrevious')?'Absent până la data raportului':r.flags.includes('billed')?'Facturat':r.metrics.documents===null?'Lună neimportată':'Fără facturare în date';
export default function ClientSales({scopeQuery='',scopeLabel='Portofoliul meu',manager=false,initialMonth,onMonthChange}:{scopeQuery?:string;scopeLabel?:string;manager?:boolean;initialMonth?:string;onMonthChange?:(month:string)=>void}){
  const [month,setMonth]=useState(()=>initialMonth||bucharestReportingMonthKey(new Date())),[q,setQ]=useState(''),[search,setSearch]=useState(''),[county,setCounty]=useState(''),[filter,setFilter]=useState<ClientFilter>('all'),[sort,setSort]=useState<ClientSort>('value'),[direction,setDirection]=useState('desc'),[page,setPage]=useState(0),[retry,setRetry]=useState(0),[selected,setSelected]=useState<string|null>(null);
  const [response,setResponse]=useState<{key:string;data:ClientSalesResult}|null>(null),[failure,setFailure]=useState<{key:string;message:string}|null>(null);
  const params=new URLSearchParams(scopeQuery);for(const [k,v] of Object.entries({month,q:search,county,filter,sort,direction,page:String(page)}))params.set(k,v);
  const query=params.toString(),key=query+'|'+retry;
  const data=response?.key===key?response.data:null,error=failure?.key===key?failure.message:'';
  const ready=data?.state==='ready'?data:null;
  useEffect(()=>{const controller=new AbortController();api<ClientSalesResult>('sales/clients?'+query,'GET',undefined,controller.signal).then(data=>{if(!controller.signal.aborted)setResponse({key,data});}).catch(e=>{if(!controller.signal.aborted)setFailure({key,message:errorMessage(e)});});return()=>controller.abort();},[query,key]);
  useEffect(()=>{const timer=setTimeout(()=>{setSearch(q);setPage(0);},250);return()=>clearTimeout(timer);},[q]);
  const selectMonth=(m:string)=>{if(m){setMonth(m);onMonthChange?.(m);setPage(0);setSelected(null);}};
  const chip=(f:ClientFilter)=><button type="button" key={f} aria-pressed={filter===f} onClick={()=>{setFilter(f);setPage(0);}}>{labels[f]} <span>{ready?(!ready.window.imported&&!['all','visited','unvisited','unvisitedPrevious','unvisitedThree','unknown'].includes(f)?'—':ready.counts[f]):'…'}</span></button>;
  return <section className="client-sales" aria-label="Raport pe clienți">
    <header><div><h2>Raport pe clienți</h2><p><strong>Portofoliu curent · {scopeLabel}</strong></p></div><button type="button" onClick={()=>setRetry(v=>v+1)}>Actualizează raportul</button></header>
    <p>Vânzările firmelor din portofoliu, din raportul pe clienți. Facturările și vizitele sunt urmărite separat.</p>
    <div className="client-sales-controls"><label>Luna raportului<input aria-label="Luna raportului pe clienți" type="month" value={month} onChange={e=>selectMonth(e.target.value)}/></label><label>Caută client<input aria-label="Caută client în raport" value={q} onChange={e=>setQ(e.target.value)} placeholder="Nume, CUI sau localitate"/></label></div>
    <details className="client-sales-advanced"><summary>Județ și sortare{county?' · '+county:''}</summary><div className="client-sales-controls"><label>Județ<select value={county} onChange={e=>{setCounty(e.target.value);setPage(0);}}><option value="">Toate județele</option>{(ready?.counties||[county].filter(Boolean)).map(c=><option key={c}>{c}</option>)}</select></label><label>Sortare<select aria-label="Sortare clienți" value={sort} onChange={e=>{setSort(e.target.value as ClientSort);setPage(0);}}><option value="value">Vânzări nete</option><option value="name">Client</option><option value="county">Județ</option><option value="documents">Facturări</option><option value="lastBilling">Ultima facturare</option><option value="previous">Luna precedentă</option></select></label><label>Ordine<select aria-label="Ordine clienți" value={direction} onChange={e=>{setDirection(e.target.value);setPage(0);}}><option value="desc">Descrescător</option><option value="asc">Crescător</option></select></label></div></details>
    {error&&<p role="alert">{error} <button type="button" onClick={()=>setRetry(v=>v+1)}>Reîncearcă</button></p>}
    {!data&&!error&&<output>Se încarcă raportul pe clienți…</output>}
    {data?.state==='unavailable'&&<p role="alert">{data.message} <button type="button" onClick={()=>setRetry(v=>v+1)}>Reîncearcă</button></p>}
    {ready&&<>
      <div className="client-sales-source"><p className="client-sales-period"><strong>{ready.window.imported?`Raport: ${date(ready.window.from)} – ${date(ready.window.to)}`:'Lună neimportată'}</strong>{ready.source.updatedAt&&<> · Actualizat {new Date(ready.source.updatedAt).toLocaleDateString('ro-RO',{timeZone:'Europe/Bucharest'})}</>}</p><details><summary>Detalii despre sursă și acoperire</summary><p>Actualizare sursă: {ready.source.updatedAt?new Date(ready.source.updatedAt).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'}):'dată indisponibilă'}. Sfârșit declarat: {date(ready.source.declaredEnd)}. Ultima tranzacție observată (național): {date(ready.source.observedEnd)}. Dată-limită a sursei: {date(ready.source.effectiveCutoff)}.</p><p>Include istoricul tuturor vânzătorilor firmei, nu doar vânzările personale ale agentului. Facturările nu sunt comenzi verificate în aplicație și nu dovedesc vizite. Perioada declarată și ultima tranzacție observată nu garantează singure un export exhaustiv.</p></details>
        <p>{!ready.window.imported?'Lună neimportată: nu interpretăm lipsa datelor drept zero vânzări sau clienți pierduți.':`${ready.window.complete?'Lună acoperită.':ready.window.covered?'Lună incompletă; comparație până la aceeași zi din lună. Zilele ulterioare nu sunt acoperite.':'Acoperire cu goluri; concluziile de absență și risc sunt suspendate.'}`}</p>
        {ready.source.latestMonth&&ready.source.latestMonth!==month&&<button type="button" onClick={()=>selectMonth(ready.source.latestMonth!)}>Ultima lună disponibilă · {ready.source.latestMonth}</button>}
        <details><summary>Acoperirea importurilor</summary>{ready.source.coverage.map((p,i)=><p key={i}>{date(p.start)} – {date(p.declaredEnd)} declarat; observat până la {date(p.observedEnd)}.</p>)}</details>
      </div>
      <div className="client-sales-cards">{[['Vânzări nete',amount(ready.totals.valueCents)],['Clienți facturați',number(ready.totals.billed)],['Facturări pozitive',number(ready.totals.documents)],['Facturări / client',number(ready.totals.perClient)],['Absenți · luna precedentă',ready.window.covered&&ready.comparisons[0].covered?number(ready.counts.absentPrevious):'—'],['Prima facturare · 60 zile',ready.window.imported?number(ready.counts.new):'—']].map(([label,value],index)=><button type="button" key={label} onClick={()=>{setFilter((['all','billed','billed','billed','absentPrevious','new'] as const)[index]);setPage(0);}}><span>{label}</span><strong>{value}</strong></button>)}</div>
      <details><summary>Calcul și asocieri: {ready.totals.unknown} necunoscute / parțiale</summary><p>Totaluri și numărători pentru căutare / județ, înainte de filtrul de stare și paginare; o singură dată pe firmă. Sumele includ retururi. {ready.totals.unknown} asocieri necunoscute / parțiale; {ready.totals.missingValues} valori lipsă. Totalurile cunoscute pot fi parțiale. Un document este identificat prin firmă, dată, gestiune și număr.</p></details>
      <div className="client-sales-visits"><strong>{ready.totals.visits} vizite înregistrate · {ready.totals.visited} firme identificate</strong>{ready.totals.visitedUnidentified>0&&<p>În plus: {ready.totals.visitedUnidentified} fișe vizitate fără CUI identificat; nu pot fi deduplicate sigur pe firmă.</p>}<p>Vizite finalizate în aplicație: {date(ready.visitRange.from)} – {date(ready.visitRange.to)}, calendar Europe/Bucharest, independent de data-limită a facturărilor.</p>{ready.noVisitRecords&&<p>Nu există vizite înregistrate în această perioadă și selecție. Aceasta nu dovedește că partenerii nu au fost vizitați fizic.</p>}</div>
      <details><summary>Comparație cu precedentele 3 luni</summary><p>Facturări: luni întregi dacă luna selectată este completă; altfel, aceeași zi-limită, ajustată pentru lunile scurte. Vizitele au propriile luni calendaristice complete. Absențele sunt piste de verificat până la data raportului, nu abandon dovedit.</p><div className="client-sales-scroll"><table><thead><tr><th>Interval facturări</th><th>Clienți</th><th>Net</th><th>Facturări</th><th>Vizite / firme</th></tr></thead><tbody>{ready.comparisons.map(c=><tr key={c.month}><th>{date(c.from)} – {date(c.to)}<small>{c.covered?'Fereastră acoperită':'Neimportat / acoperire incompletă'}</small></th><td>{number(c.billed)}</td><td>{amount(c.valueCents)}{(c.missingValues>0||c.unknown>0)&&<small>Parțial · {c.missingValues} valori lipsă, {c.unknown} asocieri necunoscute</small>}</td><td>{number(c.documents)}</td><td>{c.visits} / {c.visited}{c.visitedUnidentified>0&&<small>+ {c.visitedUnidentified} fișe fără CUI</small>}<small>{date(c.visitsFrom)} – {date(c.visitsTo)}</small></td></tr>)}</tbody></table></div></details>
    </>}
    <div className="client-sales-chips" aria-label="Filtre clienți">{clientFilters.slice(0,4).map(chip)}</div><details><summary>Mai multe filtre · clienți recenți și vizite</summary><div className="client-sales-chips">{clientFilters.slice(4).map(chip)}</div></details>
    {ready&&<><p>{ready.total} clienți · {labels[filter]}. {ready.absenceEligible?'Absențe exploratorii până la data raportului.':'Unele ferestre nu sunt acoperite; filtrele de absență afectate sunt suspendate.'}</p>
      <div className="client-sales-scroll"><table className="client-sales-table"><thead><tr><th>Client / localitate</th><th>Net lunar</th><th>Facturări</th><th>Ultima facturare</th><th>Luna precedentă*</th><th>Stare / observație</th></tr></thead><tbody>{ready.rows.map(r=><tr key={r.key}><th><button type="button" onClick={()=>setSelected(r.id)}>{r.name}</button><small>CUI {r.cui||'necunoscut'} · {r.city} · {r.counties.join(', ')}</small><small>{r.pointCount} puncte autorizate</small></th><td>{amount(r.metrics.valueCents)}{(r.metrics.missingValues>0||!r.identityComplete)&&<small>Valoare parțială / necunoscută</small>}</td><td>{number(r.metrics.documents)}</td><td>{date(r.health.lastBilling)}</td><td>{amount(r.previous.valueCents)}{(r.previous.missingValues>0||!r.identityComplete)&&<small>Parțial / necunoscut</small>}</td><td>{status(r)}<details><summary>Detalii și vânzători sursă</summary><p>{r.health.reason}</p><p>Prima facturare observată: {date(r.health.firstBilling)}. Ultima până la data raportului: {date(r.health.lastBilling)}. {number(r.health.documents)} facturări în istoric; {number(r.health.elapsedDays)} zile de la prima, {r.health.observedDays} zile acoperite continuu.</p><p>{r.health.alertEligible?'Semnal eligibil pentru verificare.':'Fără alertă eligibilă.'} Reactivare: {r.health.reactivated?'da, pauză acoperită de minimum 60 de zile':'nedemonstrată'}. {r.visits} vizite înregistrate în luna calendaristică.</p>{r.pointCount>r.points.length&&<p>Primele 20 de puncte sunt afișate aici. Restul punctelor autorizate sunt accesibile în Parteneri.</p>}{r.points.map(p=><button type="button" key={p.id} onClick={()=>setSelected(p.id)}>Fișă și vânzători sursă · {p.name}{p.city?' · '+p.city:''}</button>)}</details></td></tr>)}</tbody></table></div>
      {!ready.rows.length&&<p>Nu există clienți pentru filtrele selectate.</p>}<p>* Fereastră echivalentă din luna precedentă. Istoricul firmei include toate punctele; fișa permite și filtrarea pe punct exact.</p><nav className="client-sales-pagination" aria-label="Paginare clienți"><button type="button" disabled={!page} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>Pagina {page+1} · 50 / pagină</span><button type="button" disabled={!ready.hasMore} onClick={()=>setPage(v=>v+1)}>Următor</button></nav>
      {selected&&<Suspense fallback={<output>Se încarcă fișa…</output>}><PartnerSheet key={selected+'|'+month} id={selected} manager={manager} salesRange={{from:ready.window.from,to:ready.window.to||ready.visitRange.to}} onClose={()=>setSelected(null)} onSaved={()=>setRetry(v=>v+1)}/></Suspense>}
    </>}
  </section>;
}
