'use client';
import {useEffect,useState,useRef} from 'react';
import {api,errorMessage,money} from '@/lib/client-api';
import type {RevenueBucket,RevenueException} from '@/lib/client-sales-reconciliation';
type Report={revision?:string;explanation:string;window:{from:string;to:string|null;imported:boolean};source:{revision:string;builtAt:string};buckets:Record<string,RevenueBucket>;exceptions:RevenueException[];total:number;hasMore:boolean};
const labels:Record<string,string>={raw:'Sursă brută',consumer:'Consumatori',linkedCompany:'Firme asociate',currentPortfolio:'Portofoliu activ actual',absent:'Firme absente din CRM',inactive:'Firme doar cu puncte inactive',identity:'Identități neasociate'};
export function ClientSalesReconciliation({month}:{month:string}){
  const [open,setOpen]=useState(false),[page,setPage]=useState(0),[report,setReport]=useState<{key:string;data:Report}|null>(null),[failure,setFailure]=useState<{key:string;message:string}|null>(null);
  const revision=useRef<string|undefined>(undefined);
  const query=new URLSearchParams({month,page:String(page)}).toString(),ready=report?.key===query?report.data:null,error=failure?.key===query?failure.message:null;
  useEffect(()=>{if(!open)return;const controller=new AbortController();api<Report>('sales/clients/reconciliation?'+query+(page&&revision.current?'&revision='+encodeURIComponent(revision.current):''),'GET',undefined,controller.signal).then(data=>{if(!controller.signal.aborted){revision.current=data.revision;setReport({key:query,data});}}).catch(e=>{if(!controller.signal.aborted){if(e.status===409&&page){revision.current=undefined;setPage(0);setReport(null);}else setFailure({key:query,message:errorMessage(e)});}});return()=>controller.abort();},[open,query,page]);
  return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Reconciliere națională și excepții CRM</summary><p>Această punte acoperă sursa națională pentru luna selectată, independent de filtrele de agent, județ și căutare de mai sus.</p>{error&&<p role="alert">{error}</p>}{!ready&&!error&&open&&<p>Se calculează reconcilierea…</p>}{ready&&<><p>{ready.explanation}</p><p>{ready.window.imported?`${ready.window.from} – ${ready.window.to}`:'Lună neimportată — totalurile nu reprezintă zero vânzări.'}</p><div className="client-sales-scroll"><table><thead><tr><th>Etapă</th><th>Valoare cunoscută</th><th>Valori lipsă</th><th>Rânduri sursă</th></tr></thead><tbody>{Object.entries(ready.buckets).map(([key,b])=><tr key={key}><th>{labels[key]}</th><td>{ready.window.imported?money(b.knownCents/100):'—'}</td><td>{b.missingValues}</td><td>{b.sourceRows}</td></tr>)}</tbody></table></div><p>Revizia sursei: <code>{ready.source.revision}</code>. Centralizare: {ready.source.builtAt}.</p><a href={'/api/sales/clients/reconciliation?'+new URLSearchParams({month,format:'csv'})}>Exportă reconcilierea și toate excepțiile (CSV)</a><p>{ready.total} excepții · pagina {page+1}</p><ul>{ready.exceptions.map(r=><li key={r.key}>{labels[r.category]} · {r.companyId||r.clientCode||r.key}: {money(r.knownCents/100)} · {r.missingValues} valori lipsă. {r.reason}</li>)}</ul><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</button><button disabled={!ready.hasMore} onClick={()=>setPage(p=>p+1)}>Următor</button></>}</details>;
}
