import assert from 'node:assert/strict';
import {unzipSync,strFromU8} from 'fflate';
import { readFileSync,writeFileSync,mkdirSync } from 'node:fs';
import {randomBytes,scryptSync,randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';

const root='http://localhost:3000/api/';
const folder='../tools/qa';mkdirSync(folder,{recursive:true});
if(process.argv.includes('--prepare')) {
  const password=randomBytes(15).toString('base64url'),salt=randomBytes(16).toString('hex');
  const hash=`scrypt:${salt}:${scryptSync(password,salt,32,{N:32768,r:8,p:3,maxmem:40*1024*1024}).toString('hex')}`;
  const users=[['qa-manager','qa.manager','Manager verificare','manager','global',null,0],['qa-regional','qa.regional','Manager regional verificare','manager','assigned',null,0],['qa-agent1','qa.agent1','Agent verificare 1','agent','assigned','g-5',1],['qa-agent2','qa.agent2','Agent verificare 2','agent','assigned','g-3',0]];
  const sql=users.map(([id,name,full,role,scope,g,force])=>`INSERT OR REPLACE INTO users (id,username,name,role,manager_scope,warehouse_id,password_hash,must_change_password,active) VALUES ('${id}','${name}','${full}','${role}','${scope}',${g?`'${g}'`:'NULL'},'${hash}',${force},1);`).join('\n')+`\nINSERT OR REPLACE INTO manager_agents(manager_id,agent_id) VALUES ('qa-regional','qa-agent1');`;
  writeFileSync(folder+'/setup.sql',sql);writeFileSync(folder+'/credentials.json',JSON.stringify({password}));
  console.log('Prepared isolated QA accounts.');process.exit();
}
const {password}=JSON.parse(readFileSync(folder+'/credentials.json','utf8'));
const created=[];let checks=0;
function ok(value,message){assert.ok(value,message);checks++;}
async function call(path,method='GET',body,cookie,expected=200) {
  const options={method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})}};
  if(body&&method!=='GET'&&method!=='HEAD')options.body=JSON.stringify(body);
  const r=await fetch(root+path,options);
  let json;try{json=await r.json();}catch{json={};}
  assert.ok((Array.isArray(expected)?expected:[expected]).includes(r.status),`${method} ${path}: ${r.status} ${JSON.stringify(json).slice(0,700)}`);checks++;
  return {data:json,cookie:r.headers.get('set-cookie')?.split(';')[0],response:r};
}
async function create(kind,cookie,agentId='qa-agent1',extra={}) {const id=randomUUID();created.push(id);const r=await call('orders','POST',{id,kind,agentId,...extra},cookie,201);return r.data.order;}
async function save(o,cookie,overrides={}) {return (await call(`orders/${o.id}`,'PUT',{revision:o.revision,items:o.items.map(l=>({id:l.id,quantity:l.quantity})),serials:o.serials,clientId:o.client?.id||null,notes:o.notes,...overrides},cookie)).data.order;}
try {
  await call('orders','GET',null,null,401);
  await call('auth/login','POST',{username:'qa.agent1',password:'bad'},null,401);
  const manager=(await call('auth/login','POST',{username:'qa.manager',password})).cookie;
  const regional=(await call('auth/login','POST',{username:'qa.regional',password})).cookie;
  let agent=(await call('auth/login','POST',{username:'qa.agent1',password})).cookie;
  const agent2=(await call('auth/login','POST',{username:'qa.agent2',password})).cookie;
  await call('orders','GET',null,agent);
  await call('auth/password','POST',{currentPassword:password,password:password+'A!'},agent,403);
  const bootstrap=(await call('bootstrap','GET',null,manager)).data;
  const seedProducts=JSON.parse(readFileSync('resources/seed.json','utf8')).products;
  ok(seedProducts.length>0&&bootstrap.products.length===seedProducts.length,'All current seeded products available');
  const seedChargers=seedProducts.filter(p=>p.category==='Încărcătoare');
  ok(seedChargers.length>0&&bootstrap.products.filter(p=>p.category==='Încărcătoare').length===seedChargers.length,'Charger categories have valid Romanian text');
  const regionalBootstrap=(await call('bootstrap','GET',null,regional)).data;
  ok(regionalBootstrap.user.managerScope==='assigned','Regional manager keeps assigned scope');
  ok(regionalBootstrap.regionalSettings.partnerTo.join(',')==='distribution@example.invalid,warehouse@example.invalid'&&regionalBootstrap.regionalSettings.partnerCc.join(',')==='operations@example.invalid'&&!regionalBootstrap.regionalSettingsMixed,'Regional manager receives editable regional defaults');
  ok(JSON.stringify(regionalBootstrap.managerMailSettings)==='{"accessories":"","stands":"","sim":"","partner":""}','Regional manager starts with independent empty mail recipients');
  ok(regionalBootstrap.users.filter(u=>u.role==='agent').map(u=>u.id).join(',')==='qa-agent1','Regional manager sees only assigned agents');
  ok(regionalBootstrap.users.find(u=>u.id==='qa-regional').managedAgentIds.join(',')==='qa-agent1','Regional manager assignment is exposed to management UI');
  ok(regionalBootstrap.warehouses.map(w=>w.id).join(',')==='g-5','Regional manager sees only assigned warehouses');
  ok(bootstrap.users.find(u=>u.id==='qa-regional').managedAgentIds.join(',')==='qa-agent1','Global manager receives regional assignments');
  const initialImportStatus=(await call('admin/imports/status','GET',null,regional)).data;
  ok(initialImportStatus.sales===null&&initialImportStatus.stock===null,'Regional manager can read empty shared import status');
  await call('admin/imports/status','GET',null,agent,403);
  await call('admin/managers','POST',{},regional,403);
  const createdManagers=(await call('admin/managers','POST',{name:'Manager regional 2',username:'qa.regional2',password,agentIds:['qa-agent2']},manager)).data.users;
  let regional2=createdManagers.find(u=>u.username==='qa.regional2');
  ok(regional2?.managerScope==='assigned'&&regional2.managedAgentIds.join(',')==='qa-agent2','Global manager creates scoped regional manager');
  const regional2Cookie=(await call('auth/login','POST',{username:'qa.regional2',password})).cookie;
  let regional2Bootstrap=(await call('bootstrap','GET',null,regional2Cookie)).data;
  ok(regional2Bootstrap.users.filter(u=>u.role==='agent').map(u=>u.id).join(',')==='qa-agent2','New regional manager sees only assigned agent');
  const originalRegional2Version=regional2.profileVersion;
  const updatedManagers=(await call(`admin/managers/${regional2.id}`,'PUT',{version:regional2.profileVersion,name:'Manager regional 2',username:'qa.regional2',agentIds:['qa-agent1','qa-agent2']},manager)).data.users;
  regional2=updatedManagers.find(u=>u.id===regional2.id);
  ok(regional2.managedAgentIds.length===2,'Regional assignment supports multiple agents');
  await call(`admin/managers/${regional2.id}`,'PUT',{version:originalRegional2Version,name:'Stale',username:'qa.regional2',agentIds:[]},manager,409);
  regional2Bootstrap=(await call('bootstrap','GET',null,regional2Cookie)).data;
  ok(regional2Bootstrap.users.filter(u=>u.role==='agent').length===2,'Existing regional session immediately follows updated assignment');
  const globalProfile=bootstrap.users.find(u=>u.id==='qa-manager');
  const renamedGlobal=(await call('admin/managers/qa-manager','PUT',{version:globalProfile.profileVersion,name:'Manager global QA',username:'qa.manager.renamed'},manager)).data.users.find(u=>u.id==='qa-manager');
  ok(renamedGlobal.name==='Manager global QA'&&renamedGlobal.username==='qa.manager.renamed','Global manager can rename own account');
  await call('orders','GET',null,manager);
  await call('clients?warehouseId=g-3','GET',null,regional,404);
  await call('stock?warehouseId=g-3','GET',null,regional,404);
  ok((await call('admin/products','GET',null,regional)).data.products.length===bootstrap.products.length,'Regional manager can open the shared product catalog');
  await call('admin/settings','PUT',{weeklyLimit:7},regional,403);
  const clients=(await call('clients?warehouseId=g-5','GET',null,agent)).data.clients;
  ok(clients.length===315,'315 customers imported');
  const restricted=(await call('clients?warehouseId=g-5','GET',null,agent2)).data.clients;
  ok(restricted.length===0,'Agent cannot request another portfolio');
  await call('admin/settings','PUT',{weeklyLimit:7},agent,403);
  await call('admin/manager-mail','PUT',{accessories:'agent@example.com',stands:'',sim:''},agent,403);
  await call('admin/manager-mail','PUT',{accessories:'bad address',stands:'',sim:''},regional,400);
  const regionalMail={accessories:'regional.acc@example.com',stands:'regional.stands@example.com',sim:'regional.sim@example.com',partner:'regional.partner@example.com'};
  const pushConfig=(await call('notifications/push','GET',null,regional)).data;
  ok(typeof pushConfig.publicKey==='string'&&pushConfig.publicKey.length>40&&!('privateKey' in pushConfig),'Manager receives only public VAPID configuration');
  await call('notifications/push','GET',null,agent,403);
  await call('notifications/inbox','GET',null,agent,403);
  await call('notifications/push','POST',{endpoint:'http://example.invalid/push',keys:{p256dh:'AAAA',auth:'BBBB'}},regional,400);
  const fakePush={endpoint:'https://example.invalid/push/qa',keys:{p256dh:'AAAA',auth:'BBBB'}};
  await call('notifications/push','POST',fakePush,regional);
  let pushDb=new DatabaseSync('work/qa/mobiup.sqlite');ok(pushDb.prepare('SELECT COUNT(*) count FROM push_subscriptions WHERE user_id=?').get('qa-regional').count===1,'Manager push subscription is persisted');pushDb.close();
  await call('notifications/push','DELETE',{endpoint:fakePush.endpoint},regional);
  pushDb=new DatabaseSync('work/qa/mobiup.sqlite');ok(pushDb.prepare('SELECT COUNT(*) count FROM push_subscriptions WHERE user_id=?').get('qa-regional').count===0,'Manager can remove device push subscription');pushDb.close();
  const savedRegionalMail=(await call('admin/manager-mail','PUT',regionalMail,regional)).data.managerMailSettings;
  ok(JSON.stringify(savedRegionalMail)===JSON.stringify(regionalMail),'Regional manager can save only own document CC addresses');
  ok(JSON.stringify((await call('bootstrap','GET',null,regional)).data.managerMailSettings)===JSON.stringify(regionalMail),'Regional manager mail settings persist in bootstrap');
  const partnerRequestId=randomUUID();
  const partnerBody={requestId:partnerRequestId,company:'SC PUB4SALES SRL',location:'ZARNESTI',cui:'49088022',storeType:'MAGAZIN',contact:'SOROHAN COSMIN',phone:'0733255616',email:'',address:'STR.1 DECEMBRIE 1918 NR.4',county:'BRASOV'};
  await call('partner/mail','POST',partnerBody,regional,403);
  await call('partner/mail','POST',{...partnerBody,email:'bad address'},agent,400);
  const partnerResult=(await call('partner/mail','POST',partnerBody,agent)).data;
  ok(partnerResult.mail.to==='distribution@example.invalid,warehouse@example.invalid','Partner mail uses Distribution and Depot recipients');
  ok(partnerResult.mail.cc.join(',')==='regional.partner@example.com,operations@example.invalid','Partner mail adds assigned regional manager and operational CC');
  ok(partnerResult.mail.subject==='Creare partener nou SC PUB4SALES SRL'&&partnerResult.mail.body.includes('STR.1 DECEMBRIE 1918 NR.4'),'Partner mail subject and body use submitted partner data');
  ok(partnerResult.eml.includes('X-Unsent: 1')&&partnerResult.eml.includes('multipart/alternative'),'Partner Outlook message is generated as an unsent HTML-capable EML');
  ok(partnerResult.request.id===partnerRequestId&&partnerResult.request.status==='requested','Generating partner mail persists one requested partner record');
  const regionalInbox=(await call('notifications/inbox','GET',null,regional)).data,globalInbox=(await call('notifications/inbox','GET',null,manager)).data;
  ok(regionalInbox.count===1&&regionalInbox.items[0]?.id===partnerRequestId,'Regional inbox surfaces pending request for assigned agent');
  ok(globalInbox.count===1&&globalInbox.items[0]?.id===partnerRequestId,'Global inbox surfaces all pending partner requests');
  const scopeDb=new DatabaseSync('work/qa/mobiup.sqlite'),otherRequestId=randomUUID(),otherPayload={...partnerBody,requestId:otherRequestId,company:'OUT OF SCOPE QA',cui:'RO5500000000'};scopeDb.prepare("INSERT INTO partner_requests(id,agent_id,warehouse_id,cui_key,status,payload,created_at,updated_at,revision) VALUES (?,?,?,?,'requested',?,?,?,1)").run(otherRequestId,'qa-agent2','g-3','5500000000',JSON.stringify(otherPayload),new Date().toISOString(),new Date().toISOString());scopeDb.close();
  const scopedInbox=(await call('notifications/inbox','GET',null,regional)).data,allInbox=(await call('notifications/inbox','GET',null,manager)).data;
  ok(scopedInbox.count===1&&!scopedInbox.items.some(item=>item.id===otherRequestId),'Regional inbox excludes requests outside assigned agents');
  ok(allInbox.count===2&&allInbox.items.some(item=>item.id===otherRequestId),'Global inbox includes request outside regional scope');
  const scopeCleanup=new DatabaseSync('work/qa/mobiup.sqlite');scopeCleanup.prepare('DELETE FROM partner_requests WHERE id=?').run(otherRequestId);scopeCleanup.close();
  ok((await call(`partner/requests/${partnerRequestId}`,'GET',null,agent)).data.request.id===partnerRequestId,'Agent can retrieve own partner request by ID independent of month');
  await call(`partner/requests/${partnerRequestId}`,'GET',null,agent2,404);
  ok((await call(`partner/requests/${partnerRequestId}`,'GET',null,regional)).data.request.id===partnerRequestId,'Assigned regional manager can retrieve partner request by ID');
  const partnerRetry=(await call('partner/mail','POST',{...partnerBody,revision:partnerResult.request.revision,contact:'CONTACT ACTUALIZAT'},agent)).data;
  ok(partnerRetry.request.id===partnerRequestId&&partnerRetry.request.revision>partnerResult.request.revision,'Regenerating the same partner request updates instead of duplicating it');
  ok((await call('notifications/inbox','GET',null,regional)).data.count===1,'Regenerating the same request does not create a second pending alert');
  const globalLookup=(await call(`partner/lookup?cui=${encodeURIComponent('RO '+clients[0].cui.replace(/^RO/i,''))}`,'GET',null,agent2)).data;
  ok(globalLookup.locations.some(item=>item.id===clients[0].id),'CUI lookup searches the full customer database outside the agent portfolio');
  const samePointId=randomUUID();
  const samePointBody={requestId:samePointId,company:clients[0].name,location:clients[0].city,cui:clients[0].cui,storeType:'MAGAZIN',contact:'QA CONTACT',phone:'0700000001',email:'',address:clients[0].address,county:clients[0].county};
  const samePointRequest=(await call('partner/mail','POST',samePointBody,agent)).data.request;
  await call(`partner/requests/${samePointId}/confirm`,'POST',{revision:samePointRequest.revision},agent,403);
  const beforeSamePoint=(await call('clients','GET',null,agent)).data.clients.length;
  const samePointConfirmed=(await call(`partner/requests/${samePointId}/confirm`,'POST',{revision:samePointRequest.revision},regional)).data.request;
  const afterSamePoint=(await call('clients','GET',null,agent)).data.clients;
  ok(samePointConfirmed.status==='confirmed'&&samePointConfirmed.customerId===clients[0].id&&afterSamePoint.length===beforeSamePoint,'Confirming an existing CUI at the same location reuses the existing point without duplication');
  const newPointId=randomUUID();
  const newPointBody={...samePointBody,requestId:newPointId,company:clients[0].name+' PUNCT NOU',address:'STRADA QA PUNCT NOU NR 999'};
  const newPointRequest=(await call('partner/mail','POST',newPointBody,agent)).data.request;
  const newPointConfirmed=(await call(`partner/requests/${newPointId}/confirm`,'POST',{revision:newPointRequest.revision},regional)).data.request;
  const afterNewPoint=(await call('clients','GET',null,agent)).data.clients;
  const newPointClient=afterNewPoint.find(item=>item.id===newPointConfirmed.customerId);
  ok(newPointConfirmed.status==='confirmed'&&newPointClient?.cui===clients[0].cui&&newPointClient.address===newPointBody.address&&afterNewPoint.length===beforeSamePoint+1,'Same CUI at a different address creates a distinct work location');
  const lookupAfter=(await call(`partner/lookup?cui=${encodeURIComponent(clients[0].cui)}`,'GET',null,agent)).data;
  ok(lookupAfter.locations.length>=2,'CUI lookup shows all work locations for the same company');
  const partnerMonth=newPointRequest.createdAt.slice(0,7);
  const agentRequests=(await call(`partner/requests?month=${partnerMonth}`,'GET',null,agent)).data.requests;
  ok(agentRequests.filter(item=>[partnerRequestId,samePointId,newPointId].includes(item.id)).length===3,'Agent monthly history contains requested and confirmed partner records');
  const regionalActivity=(await call(`activity/team?month=${partnerMonth}`,'GET',null,regional)).data;
  const activityAgent=regionalActivity.agents.find(item=>item.agentId==='qa-agent1');
  ok(activityAgent.partnerRequests===3&&activityAgent.partnerConfirmed===2&&regionalActivity.partnerRequests.length===3,'Regional activity aggregates assigned-agent partner requests');
  ok(regionalActivity.agents.length===1&&!regionalActivity.agents.some(item=>item.agentId==='qa-agent2'),'Regional activity cannot expose agents outside manager scope');
  ok(regionalActivity.totals.activeAgents===1&&regionalActivity.totals.partnerRequests-regionalActivity.totals.partnerConfirmed===1,'Regional dashboard totals use real active-agent and pending-request counts');
  const activityDb=new DatabaseSync('work/qa/mobiup.sqlite');activityDb.prepare('UPDATE users SET active=0 WHERE id=?').run('qa-agent2');activityDb.close();
  const globalActivity=(await call(`activity/team?month=${partnerMonth}`,'GET',null,manager)).data;
  const zeroPartnerAgent=globalActivity.agents.find(item=>item.agentId==='qa-agent2');
  ok(zeroPartnerAgent?.partnerRequests===0&&zeroPartnerAgent.active===false,'Global activity includes zero-partner agents and exposes inactive state');
  ok(globalActivity.totals.activeAgents===globalActivity.agents.filter(item=>item.active).length,'Active-agent KPI excludes inactive accounts');
  const activityRestore=new DatabaseSync('work/qa/mobiup.sqlite');activityRestore.prepare('UPDATE users SET active=1 WHERE id=?').run('qa-agent2');activityRestore.close();
  const dashboardRequestId=randomUUID(),dashboardRequest=(await call('partner/mail','POST',{...partnerBody,requestId:dashboardRequestId,company:'DASHBOARD REFRESH QA',cui:'RO6677889900',address:'Strada Dashboard 7'},agent)).data.request;
  const dashboardBefore=(await call(`activity/team?month=${partnerMonth}`,'GET',null,regional)).data, inboxBefore=(await call('notifications/inbox','GET',null,regional)).data.count;
  await call(`partner/requests/${dashboardRequestId}/confirm`,'POST',{revision:dashboardRequest.revision},regional);
  const dashboardAfter=(await call(`activity/team?month=${partnerMonth}`,'GET',null,regional)).data, inboxAfter=(await call('notifications/inbox','GET',null,regional)).data.count;
  ok(dashboardAfter.totals.partnerConfirmed===dashboardBefore.totals.partnerConfirmed+1&&dashboardAfter.totals.partnerRequests-dashboardAfter.totals.partnerConfirmed===dashboardBefore.totals.partnerRequests-dashboardBefore.totals.partnerConfirmed-1,'Partner confirmation immediately refreshes dashboard confirmed/pending read-model counts');
  ok(inboxAfter===inboxBefore-1,'Partner confirmation immediately removes the request from manager inbox count');
  await call(`activity/team?month=${partnerMonth}`,'GET',null,agent,403);
  const countyPointId=randomUUID(),countyPointBody={...samePointBody,requestId:countyPointId,county:`${clients[0].county||'PRAHOVA'} QA DISTINCT`};
  const countyPointRequest=(await call('partner/mail','POST',countyPointBody,agent)).data.request;
  const countyPointConfirmed=(await call(`partner/requests/${countyPointId}/confirm`,'POST',{revision:countyPointRequest.revision},regional)).data.request;
  const countyPointClient=(await call('clients','GET',null,agent)).data.clients.find(item=>item.id===countyPointConfirmed.customerId);
  ok(countyPointConfirmed.customerId!==clients[0].id&&countyPointClient?.county===countyPointBody.county&&countyPointClient.address===clients[0].address,'Same CUI, city and address in a different county creates a distinct work location');
  const legacyCustomerId='legacy-county-qa',legacyClient={id:legacyCustomerId,warehouseId:'g-5',warehouseIds:['g-5'],name:'LEGACY COUNTY QA',cui:'RO5566778899',city:'Dumbrava',county:'',address:'Strada Legacy 1',route:''};
  const legacyDb=new DatabaseSync('work/qa/mobiup.sqlite');legacyDb.prepare('INSERT OR REPLACE INTO customers(id,warehouse_id,data,active) VALUES (?,?,?,1)').run(legacyCustomerId,'g-5',JSON.stringify(legacyClient));legacyDb.close();
  const legacyRequestId=randomUUID(),legacyBody={...partnerBody,requestId:legacyRequestId,company:'LEGACY COUNTY QA',cui:legacyClient.cui,location:legacyClient.city,county:'Timiș',address:legacyClient.address};
  const legacyRequest=(await call('partner/mail','POST',legacyBody,agent)).data.request;
  await call(`partner/requests/${legacyRequestId}/confirm`,'POST',{revision:legacyRequest.revision},regional,409);
  const legacyConfirmed=(await call(`partner/requests/${legacyRequestId}/confirm`,'POST',{revision:legacyRequest.revision,locationResolution:'new'},regional)).data.request;
  ok(legacyConfirmed.customerId!==legacyCustomerId,'Legacy location with missing county requires explicit resolution instead of automatic association');
  const legacyCleanup=new DatabaseSync('work/qa/mobiup.sqlite');legacyCleanup.prepare('DELETE FROM customers WHERE id=?').run(legacyCustomerId);legacyCleanup.close();
  const boundaryId=randomUUID(),boundaryBody={...partnerBody,requestId:boundaryId,cui:'RO9988776655',company:'BOUNDARY MONTH QA'};
  await call('partner/mail','POST',boundaryBody,agent);
  const qaDb=new DatabaseSync('work/qa/mobiup.sqlite');
  qaDb.prepare('UPDATE partner_requests SET created_at=?,updated_at=? WHERE id=?').run('2026-08-31T21:30:00.000Z','2026-08-31T21:30:00.000Z',boundaryId);qaDb.close();
  const augustBoundary=(await call('partner/requests?month=2026-08','GET',null,agent)).data.requests;
  const septemberBoundary=(await call('partner/requests?month=2026-09','GET',null,agent)).data.requests;
  ok(!augustBoundary.some(item=>item.id===boundaryId)&&septemberBoundary.some(item=>item.id===boundaryId),'Partner activity at 1 September 00:30 Bucharest belongs only to September');
  let partnerSim=await create('sim',agent);partnerSim=await save(partnerSim,agent,{clientId:newPointClient.id,serials:['89400000000000000991']});
  ok(partnerSim.client.id===newPointClient.id&&partnerSim.client.address===newPointBody.address,'Confirmed work location is immediately selectable in a SIM draft');
  const cfg={...bootstrap.settings,accessoriesEmail:'accessories@example.com',standsEmail:'stands@example.com',simEmail:'sim@example.com',accessoriesCc:['acc1@example.com','','acc3@example.com','acc4@example.com'],standsCc:['std1@example.com','std2@example.com','std3@example.com','std4@example.com'],simCc:['sim1@example.com','sim2@example.com'],partnerTo:['partner.ops1@example.com','partner.ops2@example.com'],partnerCc:['partner.cc@example.com']};
  await call('admin/settings','PUT',cfg,manager);
  const savedCfg=(await call('bootstrap','GET',null,manager)).data.settings;
  ok(JSON.stringify(savedCfg)===JSON.stringify(cfg),'To/CC persist independently, including blank slots');
  const configuredPartnerId=randomUUID();
  const configuredPartner=(await call('partner/mail','POST',{...partnerBody,requestId:configuredPartnerId,cui:'RO7788990011',company:'CONFIGURED PARTNER QA'},agent)).data;
  ok(configuredPartner.mail.to==='partner.ops1@example.com,partner.ops2@example.com','Partener nou uses globally configured To recipients');
  ok(configuredPartner.mail.cc.join(',')==='regional.partner@example.com,partner.cc@example.com','Partener nou combines assigned regional manager with globally configured operational CC');
  await call('admin/settings','PUT',{...cfg,partnerTo:[]},manager,400);
  await call('admin/settings','PUT',{...cfg,partnerCc:['a@example.com','b@example.com']},manager,400);
  await call('admin/settings','PUT',{...cfg,simCc:['a@example.com','b@example.com','c@example.com']},manager,400);
  await call('admin/settings','PUT',{...cfg,accessoriesCc:['a@example.com\r\nBcc: injected@example.com']},manager,400);
  await call('admin/settings','PUT',{...cfg,standsCc:'wrong'},manager,400);
  const {accessoriesCc:_accessoriesCc,standsCc:_standsCc,simCc:_simCc,partnerTo:_partnerTo,partnerCc:_partnerCc,...legacyCfg}=cfg;
  await call('admin/settings','PUT',legacyCfg,manager);
  const legacySaved=(await call('bootstrap','GET',null,manager)).data.settings;
  ok(legacySaved.standsCc.length===4&&legacySaved.partnerTo.join(',')===cfg.partnerTo.join(',')&&legacySaved.partnerCc.join(',')===cfg.partnerCc.join(','),'Older settings requests preserve existing operational recipients');

  let acc=await create('accessories',manager);
  await call(`orders/${acc.id}`,'GET',null,regional);
  await call('orders','POST',{id:randomUUID(),kind:'accessories',agentId:'qa-agent2'},regional,404);
  await call(`orders/${acc.id}`,'GET',null,agent2,404);
  await call(`orders/${acc.id}/excel`,'GET',null,agent,400);
  await call(`orders/${acc.id}`,'PUT',{revision:acc.revision,items:[{id:'acc-2',quantity:-1}]},agent,400);
  await call(`orders/${acc.id}`,'PUT',{revision:acc.revision,items:[{id:'acc-2',quantity:1.5}]},agent,400);
  acc=await save(acc,agent,{items:[{id:'acc-2',quantity:3,price:0},{id:'acc-18',quantity:2}],notes:'Verificare export QA'});
  ok(acc.items[0].price>0,'Server owns catalog pricing');
  await call(`orders/${acc.id}`,'PUT',{revision:1,items:[]},agent,409);
  const result=(await call(`orders/${acc.id}/finalize`,'POST',{revision:acc.revision},agent)).data;
  acc=result.order;
  ok(result.mail.to===cfg.accessoriesEmail&&result.mail.cc.length===4&&result.mail.cc.includes(regionalMail.accessories),'Accessories recipients include operational CC plus assigned manager');
  ok(!result.mail.subject.includes(acc.number)&&!result.mail.body.includes(acc.number)&&!result.mail.body.includes('acc-2')&&!result.mail.body.includes('Mulțumesc'),'Accessories mail hides order number, line details and signature');
  ok(new URL(result.mail.mailto).searchParams.get('cc')===[...cfg.accessoriesCc.filter(Boolean),regionalMail.accessories].join(','),'mailto contains operational and manager CC recipients');
  const message=await fetch(root+`orders/${acc.id}/eml`,{headers:{Cookie:agent}}).then(r=>r.text());
  ok(message.includes('To: accessories@example.com\r\nCc: acc1@example.com, acc3@example.com, acc4@example.com, regional.acc@example.com\r\n'),'EML has distinct To and merged operational/manager Cc headers');
  const peerUsers=(await call('admin/managers','POST',{name:'Manager regional partajat',username:'qa.regional.peer',password,agentIds:['qa-agent1']},manager)).data.users;
  const peerManager=peerUsers.find(u=>u.username==='qa.regional.peer'),peerCookie=(await call('auth/login','POST',{username:'qa.regional.peer',password})).cookie;
  await call('admin/managers','POST',{name:'Manager altă regiune',username:'qa.regional.other',password,agentIds:['qa-agent2']},manager);
  const otherCookie=(await call('auth/login','POST',{username:'qa.regional.other',password})).cookie;
  await call('admin/manager-mail','PUT',{accessories:'other.region@example.com',stands:'other.region@example.com',sim:'other.region@example.com',partner:'other.region@example.com'},otherCookie);
  const regionalA={accessoriesEmail:'region-a@example.com',standsEmail:cfg.standsEmail,simEmail:cfg.simEmail,accessoriesCc:['region-a-cc@example.com','','',''],standsCc:[...cfg.standsCc],simCc:[...cfg.simCc],partnerTo:[...cfg.partnerTo],partnerCc:[...cfg.partnerCc]};
  await call('admin/regional-settings','PUT',regionalA,agent,403);
  await call('admin/regional-settings','PUT',regionalA,manager,403);
  await call('admin/regional-settings','PUT',regionalA,regional);
  const peerBootstrap=(await call('bootstrap','GET',null,peerCookie)).data;
  ok(peerManager&&peerBootstrap.regionalSettings.accessoriesEmail==='region-a@example.com'&&!peerBootstrap.regionalSettingsMixed,'Managers with the same agent scope share regional recipient settings');
  const otherBootstrap=(await call('bootstrap','GET',null,otherCookie)).data;
  ok(otherBootstrap.regionalSettings.accessoriesEmail===cfg.accessoriesEmail&&!otherBootstrap.regionalSettingsMixed,'A manager from another region keeps independent recipient settings');
  const mixedBootstrap=(await call('bootstrap','GET',null,regional2Cookie)).data;
  ok(mixedBootstrap.regionalSettingsMixed===true,'A manager spanning differently configured agent groups is warned about mixed regional routing');
  const regionalB={...regionalA,accessoriesEmail:'region-b@example.com',accessoriesCc:['region-b-cc@example.com','','','']};
  await call('admin/regional-settings','PUT',regionalB,peerCookie);
  const sharedAfterPeer=(await call('bootstrap','GET',null,regional)).data;
  ok(sharedAfterPeer.regionalSettings.accessoriesEmail==='region-b@example.com'&&!sharedAfterPeer.regionalSettingsMixed,'Either manager sharing a region can edit the common routing');
  const regionalOrderMail=(await call(`orders/${acc.id}/mail`,'GET',null,agent)).data.mail;
  ok(regionalOrderMail.to==='region-b@example.com'&&regionalOrderMail.cc.includes('region-b-cc@example.com')&&regionalOrderMail.cc.includes(regionalMail.accessories)&&!regionalOrderMail.cc.includes('other.region@example.com'),'Order mail uses the shared regional override and excludes managers from another region');
  const routingCleanup=new DatabaseSync('work/qa/mobiup.sqlite');routingCleanup.prepare("DELETE FROM settings WHERE key='agent-mail:qa-agent1'").run();routingCleanup.close();
ok(acc.status==='finalized'&&!!acc.finalizedAt,'Finalization persisted');
  await call(`orders/${acc.id}/finalize`,'POST',{revision:acc.revision},agent);
  await call(`orders/${acc.id}`,'PUT',{revision:acc.revision,items:[]},agent,409);
  const exported=await fetch(root+`orders/${acc.id}/excel`,{headers:{Cookie:agent}});
  ok(exported.ok&&exported.headers.get('content-type').includes('spreadsheet'),'Excel download');const accessoryBytes=Buffer.from(await exported.arrayBuffer());writeFileSync(folder+'/accessories.xlsx',accessoryBytes);const accessorySheet=strFromU8(unzipSync(new Uint8Array(accessoryBytes))['xl/worksheets/sheet1.xml']);ok(!accessorySheet.includes('state="frozen"')&&!accessorySheet.includes(acc.number),'Accessories Excel is unfrozen and hides order number');
  const copy=await create('accessories',agent,'qa-agent1',{sourceOrderId:acc.id});
  ok(copy.status==='draft'&&copy.items.length===2,'Copy is editable draft with source quantities');
  await call(`orders/${copy.id}/finalize`,'POST',{revision:copy.revision},agent);
  let third=await create('accessories',agent);third=await save(third,agent,{items:[{id:'acc-2',quantity:1}]});
  await call(`orders/${third.id}/finalize`,'POST',{revision:third.revision},agent,409);
  ok((await call(`orders/${third.id}`,'GET',null,agent)).data.order.status==='draft','Limit failure leaves draft');
  let stand=await create('stands',agent);stand=await save(stand,agent,{items:[{id:'stand-9',quantity:1},{id:'stand-10',quantity:2}]});
  stand=(await call(`orders/${stand.id}/finalize`,'POST',{revision:stand.revision},agent)).data.order;
  const standMail=(await call(`orders/${stand.id}/mail`,'GET',null,agent)).data.mail;
  ok(standMail.to===cfg.standsEmail&&standMail.cc.length===5&&standMail.cc.includes(regionalMail.stands),'Stand order includes assigned manager CC');
  ok(standMail.body.includes('de agatat')&&standMail.body.includes('de tejghea'),'Duplicate SKU rows kept distinct in email');
  const standFile=await fetch(root+`orders/${stand.id}/excel`,{headers:{Cookie:agent}});writeFileSync(folder+'/stands.xlsx',Buffer.from(await standFile.arrayBuffer()));
  const serial1='08940000000000000001',serial2='89400000000000000002';
  let sim=await create('sim',agent);await call(`orders/${sim.id}`,'PUT',{revision:1,clientId:clients[0].id,serials:[serial1,serial1]},agent,400);
  sim=await save(sim,agent,{clientId:clients[0].id,serials:[serial1,serial2]});
  sim=(await call(`orders/${sim.id}/finalize`,'POST',{revision:sim.revision},agent)).data.order;
  ok(sim.client.cui===clients[0].cui&&sim.serials[0]===serial1,'Client and exact serials preserved');
  const simMail=(await call(`orders/${sim.id}/mail`,'GET',null,agent)).data.mail;ok(simMail.to===cfg.simEmail&&simMail.cc.length===3&&simMail.cc.includes(regionalMail.sim),'SIM note includes assigned manager CC');ok(simMail.subject.includes(clients[0].cui)&&simMail.body.includes(serial1),'SIM email includes CUI and serials');
  const simFile=await fetch(root+`orders/${sim.id}/excel`,{headers:{Cookie:agent}});writeFileSync(folder+'/sim.xlsx',Buffer.from(await simFile.arrayBuffer()));
  let combined=await create('combined',agent);
  await call(`orders/${combined.id}`,'PUT',{revision:combined.revision,items:[],standItems:[],clientId:clients[1].id,serials:['89400000000000000111']},agent,400);
  await call('admin/settings','PUT',{...cfg,weeklyLimit:3},manager);
  combined=await save(combined,agent,{items:[{id:'acc-2',quantity:2}],standItems:[{id:'stand-9',quantity:123}],notes:'Livrare la gestiune'});
  combined=(await call(`orders/${combined.id}/finalize`,'POST',{revision:combined.revision},agent)).data.order;
  const combinedMail=(await call(`orders/${combined.id}/mail`,'GET',null,agent)).data.mail;
  ok(combinedMail.body.includes('cartele, telefoane & standuri')&&!combinedMail.body.includes('SIM 0')&&combinedMail.body.includes('accesorii'),'Combined mail identifies stock sections without client SIM notes');
  ok(combinedMail.to===cfg.accessoriesEmail+','+cfg.standsEmail&&combinedMail.cc.length===9&&combinedMail.cc.includes(regionalMail.accessories)&&combinedMail.cc.includes(regionalMail.stands),'Combined mail merges operational and assigned manager recipients');
  const combinedFile=await fetch(root+`orders/${combined.id}/excel`,{headers:{Cookie:agent}});const combinedBytes=new Uint8Array(await combinedFile.arrayBuffer());const combinedZip=unzipSync(combinedBytes);
  ok(combinedFile.ok&&!!combinedZip['xl/worksheets/sheet2.xml']&&strFromU8(combinedZip['xl/workbook.xml']).includes('Cartele, telefoane')&&strFromU8(combinedZip['xl/_rels/workbook.xml.rels']).includes('sheet2.xml'),'Combined Excel has a second order sheet');
  writeFileSync(folder+'/combined.xlsx',combinedBytes);
  ok(combinedBytes.length<250000,'Combined export stays below 250 KB without images');
  ok(!Object.keys(combinedZip).some(n=>n.startsWith('xl/media/')||n.startsWith('xl/drawings/')||n==='xl/calcChain.xml'),'Export contains no images, drawings or stale calculation chain');
  const bookXml=strFromU8(combinedZip['xl/workbook.xml']);
  const sheetIds=[...bookXml.matchAll(/sheetId="(\d+)"/g)].map(m=>m[1]);
  ok(bookXml.includes('name="Accesorii"')&&new Set(sheetIds).size===2&&sheetIds.length===2,'Accessory sheet is renamed and sheet IDs are unique');
  const stockXml=strFromU8(combinedZip['xl/worksheets/sheet2.xml']);
  ok(!stockXml.includes('AVIZ')&&!stockXml.includes('Serie SIM')&&stockXml.includes('mergeCells')&&stockXml.includes('showGridLines="0"')&&stockXml.includes('<v>123</v>'),'Stock sheet is styled, preserves quantity and excludes client SIM flow');
  const combinedCopy=await create('combined',agent,'qa-agent1',{sourceOrderId:combined.id});
  ok(combinedCopy.items[0].quantity===2&&combinedCopy.standItems[0].quantity===123,'Combined copy preserves both stock sections');
  await call('admin/settings','PUT',cfg,manager);
  const originalClient=(await call('clients?warehouseId=g-5','GET',null,manager)).data.clients.find(c=>c.id===clients[0].id);
  const portfolioBeforeMove=(await call('bootstrap','GET',null,manager)).data.users;
  const agent1CountBefore=portfolioBeforeMove.find(u=>u.id==='qa-agent1').clientCount,agent2CountBefore=portfolioBeforeMove.find(u=>u.id==='qa-agent2').clientCount;
  const clientUpdate={...originalClient,agentId:'qa-agent2',name:'MAGAZIN EDITAT',cui:'RO00123456',address:'Strada Nouă 12',county:'Ilfov',city:'Voluntari',route:'R9'};
  await call(`admin/clients/${originalClient.id}`,'PUT',clientUpdate,agent,403);
  await call(`admin/clients/${originalClient.id}`,'PUT',{...clientUpdate,name:''},manager,400);
  await call(`admin/clients/${originalClient.id}`,'PUT',{...clientUpdate,agentId:'qa-manager'},manager,400);
  let pendingClientMove=await create('sim',agent);
  pendingClientMove=await save(pendingClientMove,agent,{clientId:originalClient.id,serials:['89400000000000000009']});
  const moved=(await call(`admin/clients/${originalClient.id}`,'PUT',clientUpdate,manager)).data;
  ok(moved.client.id===originalClient.id&&moved.client.warehouseId==='g-3'&&moved.client.cui==='RO00123456','Client edited and transferred without losing identity or leading zeros');
  ok(moved.users.find(u=>u.id==='qa-agent1').clientCount===agent1CountBefore-1&&moved.users.find(u=>u.id==='qa-agent2').clientCount===agent2CountBefore+1,'Portfolio counts follow transfer');
  ok(!(await call('clients','GET',null,agent)).data.clients.some(c=>c.id===originalClient.id),'Old agent no longer sees transferred client');
  const received=(await call('clients','GET',null,agent2)).data.clients.find(c=>c.id===originalClient.id);
  ok(received.name==='MAGAZIN EDITAT'&&received.address==='Strada Nouă 12'&&received.city==='Voluntari'&&received.county==='Ilfov'&&received.route==='R9','New agent sees every edited field');
  ok((await call(`orders/${sim.id}`,'GET',null,manager)).data.order.client.name===originalClient.name,'Existing finalized SIM snapshot survives client edits and transfer');
  await call(`orders/${pendingClientMove.id}/finalize`,'POST',{revision:pendingClientMove.revision},agent,409);
  await call(`admin/clients/${originalClient.id}`,'PUT',{...originalClient,agentId:'qa-agent1'},manager,409);
  const returned=(await call(`admin/clients/${originalClient.id}`,'PUT',{...moved.client,agentId:'qa-agent1'},manager)).data.client;
  await call(`orders/${pendingClientMove.id}/finalize`,'POST',{revision:pendingClientMove.revision},agent,409);
  pendingClientMove=await save(pendingClientMove,agent,{clientId:originalClient.id});
  const refreshedFinal=(await call(`orders/${pendingClientMove.id}/finalize`,'POST',{revision:pendingClientMove.revision},agent)).data.order;
  ok(refreshedFinal.client.name==='MAGAZIN EDITAT','Reselecting client refreshes draft before finalization');
  await call(`admin/clients/${originalClient.id}`,'PUT',{...originalClient,version:returned.version,agentId:'qa-agent1'},manager);
  let duplicate=await create('sim',agent);duplicate=await save(duplicate,agent,{clientId:clients[0].id,serials:[serial1]});
  await call(`orders/${duplicate.id}/finalize`,'POST',{revision:duplicate.revision},agent,409);
  ok((await call(`orders/${duplicate.id}`,'GET',null,agent)).data.order.status==='draft','Duplicate serial rolls back finalization');
  const simCopy=await create('sim',agent,'qa-agent1',{sourceOrderId:sim.id});ok(simCopy.serials.length===0&&simCopy.client.id===sim.client.id,'Copy SIM retains customer and clears serials');
  let concurrent=await create('sim',agent);concurrent=await save(concurrent,agent,{clientId:clients[0].id,serials:['89400000000000000003']});
  await Promise.all([call(`orders/${concurrent.id}/finalize`,'POST',{revision:concurrent.revision},agent),call(`orders/${concurrent.id}/finalize`,'POST',{revision:concurrent.revision},agent)]);
  const concurrentId=randomUUID();created.push(concurrentId);
  const twoCreates=await Promise.all([call('orders','POST',{id:concurrentId,kind:'stands'},agent,[200,201]),call('orders','POST',{id:concurrentId,kind:'stands'},agent,[200,201])]);
  ok(twoCreates[0].data.order.id===twoCreates[1].data.order.id,'Concurrent creates share one idempotent draft');
  const importPayload={warehouseId:'g-3',clients:[{name:'CLIENT QA',cui:'RO001234',city:'TEST',county:'TEST',address:'TEST',route:'1'}]};
  const importResult=(await call('admin/import-clients','POST',importPayload,manager)).data;
  ok(importResult.count===1,'Portfolio import committed');
  const importedClient=(await call('clients','GET',null,agent2)).data.clients[0];
  ok(importedClient.cui==='RO001234','Imported CUI preserved as text');
  await call('admin/import-clients','POST',importPayload,manager);
  ok((await call('clients','GET',null,agent2)).data.clients[0].id===importedClient.id,'Reimport of the same county-aware location preserves the customer id');
  const eml=await fetch(root+`orders/${sim.id}/eml`,{headers:{Cookie:agent}});const emlText=await eml.text();ok(emlText.includes('X-Unsent: 1')&&emlText.includes('Content-Disposition: attachment'),'MIME draft contains attachment');
  const cross=await fetch(root+'orders',{method:'POST',headers:{Cookie:agent,'Content-Type':'application/json',Origin:'https://other.invalid'},body:'{}'});ok(cross.status===403,'Cross-origin write rejected');
  const own=(await call('orders','GET',null,agent2)).data.orders;ok(!own.some(o=>created.includes(o.id)),'Agent history is scoped');
  const all=(await call('orders','GET',null,manager)).data.orders;ok(created.every(id=>all.some(o=>o.id===id)),'Manager sees all test orders');
  await call(`orders/${acc.id}`,'DELETE',{revision:acc.revision},agent,403);
  await call(`orders/${acc.id}`,'DELETE',{revision:acc.revision-1},manager,409);
  ok((await call(`orders/${acc.id}`,'GET',null,manager)).data.order.status==='finalized','Stale delete leaves order intact');
  const draftForDelete=twoCreates[0].data.order;
  const agentDraft=await create('stands',agent);
  await call(`orders/${agentDraft.id}`,'DELETE',{revision:agentDraft.revision},agent);
  await call(`orders/${agentDraft.id}`,'GET',null,manager,404);
  await call(`orders/${draftForDelete.id}`,'DELETE',{revision:draftForDelete.revision},manager);
  await call(`orders/${draftForDelete.id}`,'PUT',{revision:draftForDelete.revision,items:[]},agent,404);
  await call(`orders/${sim.id}`,'DELETE',{revision:sim.revision},manager);
  await call(`orders/${sim.id}`,'GET',null,manager,404);
  await call(`orders/${sim.id}/excel`,'GET',null,agent,404);
  await call(`orders/${sim.id}/mail`,'GET',null,manager,404);
  await call('orders','POST',{id:randomUUID(),kind:'sim',sourceOrderId:sim.id},agent,404);
  const afterDelete=(await call('orders','GET',null,manager)).data.orders;
  ok(!afterDelete.some(o=>[sim.id,draftForDelete.id].includes(o.id)),'Deleted drafts and finalized notes disappear from history');
  const agentAfterDelete=(await call('orders','GET',null,agent)).data.orders;
  ok(!agentAfterDelete.some(o=>o.id===sim.id),'Deleted note disappears from agent history');
  await call(`orders/${duplicate.id}/finalize`,'POST',{revision:duplicate.revision},agent);
  await call(`orders/${acc.id}`,'DELETE',{revision:acc.revision},manager);
  await call(`orders/${acc.id}/eml`,'GET',null,manager,404);
  const sharedOriginal=(await call('clients?warehouseId=g-5','GET',null,manager)).data.clients.find(c=>c.id===clients[1].id);
  await call(`admin/clients/${sharedOriginal.id}`,'PUT',{...sharedOriginal,agentIds:[]},manager,400);
  const shared=(await call(`admin/clients/${sharedOriginal.id}`,'PUT',{...sharedOriginal,agentIds:['qa-agent1','qa-agent2']},manager)).data.client;
  ok(shared.warehouseIds.length===2,'Single work location assigned to both portfolios');
  const one=(await call('clients','GET',null,agent)).data.clients.find(c=>c.id===shared.id);
  const two=(await call('clients','GET',null,agent2)).data.clients.find(c=>c.id===shared.id);
  ok(one.id===two.id&&one.warehouseId==='g-5'&&two.warehouseId==='g-3','Both agents see same record with their own warehouse context');
  const regionalShared=(await call('clients?warehouseId=g-5','GET',null,regional)).data.clients.find(c=>c.id===shared.id);
  const regionalEdit=(await call(`admin/clients/${shared.id}`,'PUT',{...regionalShared,sourceWarehouseId:'g-5',agentIds:['qa-agent1']},regional)).data.client;
  ok(regionalEdit.warehouseIds.includes('g-5')&&regionalEdit.warehouseIds.includes('g-3'),'Regional client edit preserves shared portfolios outside its scope');
  const updatedShared=(await call(`admin/clients/${shared.id}`,'PUT',{...regionalEdit,name:'PUNCT COMUN QA',agentIds:['qa-agent1','qa-agent2']},manager)).data.client;
  ok((await call('clients','GET',null,agent2)).data.clients.find(c=>c.id===shared.id).name==='PUNCT COMUN QA','Editing shared data is visible in second portfolio');
  await call('admin/import-clients','POST',{warehouseId:'g-3',clients:[{name:'TEST',cui:'001',city:'TEST',county:'',address:'',route:''}]},manager,409);
  let sharedNote=await create('sim',agent2,'qa-agent2');sharedNote=await save(sharedNote,agent2,{clientId:shared.id,serials:['89400000000000000777']});
  sharedNote=(await call(`orders/${sharedNote.id}/finalize`,'POST',{revision:sharedNote.revision},agent2)).data.order;
  ok(sharedNote.warehouseId==='g-3'&&sharedNote.client.warehouseId==='g-3','Second agent finalizes shared client in own warehouse');
  await call(`orders/${sharedNote.id}`,'GET',null,agent,404);
  let removedOwnerDraft=await create('sim',agent);removedOwnerDraft=await save(removedOwnerDraft,agent,{clientId:shared.id,serials:['89400000000000000778']});
  const onlySecond=(await call(`admin/clients/${shared.id}`,'PUT',{...updatedShared,agentIds:['qa-agent2']},manager)).data.client;
  ok(!(await call('clients','GET',null,agent)).data.clients.some(c=>c.id===shared.id),'Unchecking an agent removes only that portfolio access');
  ok((await call('clients','GET',null,agent2)).data.clients.some(c=>c.id===shared.id),'Other agent retains shared point');
  await call(`orders/${removedOwnerDraft.id}/finalize`,'POST',{revision:removedOwnerDraft.revision},agent,409);
  ok((await call(`orders/${sharedNote.id}`,'GET',null,agent2)).data.order.client.name==='PUNCT COMUN QA','Finalized shared-client note remains intact');
  await call(`admin/clients/${shared.id}`,'PUT',{...sharedOriginal,version:onlySecond.version,agentIds:['qa-agent1']},manager);
  const originalProfile=(await call('bootstrap','GET',null,manager)).data.users.find(u=>u.id==='qa-agent1');
  const profileBody={name:'Agent actualizat QA',warehouseName:'Gestiune QA',siteCode:'001-QA',version:originalProfile.profileVersion};
  await call('admin/users/qa-agent1','PUT',profileBody,agent,403);
  await call('admin/users/qa-agent1','PUT',{...profileBody,name:''},manager,400);
  const changedProfile=(await call('admin/users/qa-agent1','PUT',profileBody,manager)).data.users.find(u=>u.id==='qa-agent1');
  ok(changedProfile.name===profileBody.name&&changedProfile.warehouseName===profileBody.warehouseName&&changedProfile.siteCode==='001-QA','Manager edits all three agent fields');
  ok(changedProfile.warehouseId===originalProfile.warehouseId&&changedProfile.username===originalProfile.username&&changedProfile.clientCount===originalProfile.clientCount,'Profile edit preserves account and portfolio');
  await call('admin/users/qa-agent1','PUT',profileBody,manager,409);
  const accountPassword=password+'Account!';
  const accountUpdated=(await call('admin/users/qa-agent1','PUT',{version:changedProfile.profileVersion,username:'qa.agent1.updated',password:accountPassword},manager)).data.users.find(u=>u.id==='qa-agent1');
  ok(accountUpdated.username==='qa.agent1.updated'&&!accountUpdated.mustChangePassword,'Manager can change an agent username and password without forcing agent rotation');
  ok(accountUpdated.profileVersion!==changedProfile.profileVersion,'Agent account changes advance administrative revision');
  await call('admin/users/qa-agent1','PUT',{version:changedProfile.profileVersion,username:'qa.agent1.stale',password:accountPassword+'Stale!'},manager,409);
  const updatedAgent=(await call('auth/login','POST',{username:'qa.agent1.updated',password:accountPassword})).cookie;
  await call('orders','GET',null,updatedAgent);
  await call('auth/password','POST',{currentPassword:accountPassword,password:accountPassword+'Agent!'},updatedAgent,403);
  const resetPassword=password+'Reset!';
  const resetUsers=(await call('admin/users','POST',{action:'reset',id:'qa-agent1',version:accountUpdated.profileVersion,password:resetPassword},manager)).data.users;
  const resetProfile=resetUsers.find(u=>u.id==='qa-agent1');
  ok(resetProfile.profileVersion!==accountUpdated.profileVersion,'Password reset advances administrative revision');
  const resetAgent=(await call('auth/login','POST',{username:'qa.agent1.updated',password:resetPassword})).cookie;
  await call('orders','GET',null,resetAgent);
  await call('auth/password','POST',{currentPassword:resetPassword,password:resetPassword+'Agent!'},resetAgent,403);
  const restoredAccount=(await call('admin/users/qa-agent1','PUT',{version:resetProfile.profileVersion,username:'qa.agent1',password:password+'A!'},manager)).data.users.find(u=>u.id==='qa-agent1');
  agent=(await call('auth/login','POST',{username:'qa.agent1',password:password+'A!'})).cookie;
  await call('auth/password','POST',{currentPassword:password+'A!',password:password+'B!'},agent,403);
  const profileOrder=await create('stands',agent);
  ok(profileOrder.agentName===profileBody.name&&profileOrder.warehouseName===profileBody.warehouseName,'New order uses updated agent and warehouse names');
  await call('admin/users/qa-agent1','PUT',{name:originalProfile.name,warehouseName:originalProfile.warehouseName,siteCode:originalProfile.siteCode,version:restoredAccount.profileVersion},manager);
  const productBody={code:'QA-CUSTOM',name:'Produs nou QA',brand:'QA',category:'Categoria QA',kind:'stands',price:12.1,netPrice:10};
  await call('admin/products','GET',null,agent,403);
  await call('admin/products','POST',productBody,agent,403);
  const regionalProductBody={code:'QA-REGIONAL',name:'Produs manager regional QA',brand:'QA',category:'Categoria QA',kind:'stands',price:9.68,netPrice:8};
  const regionalCatalog=(await call('admin/products','POST',regionalProductBody,regional)).data.products;
  const regionalProduct=regionalCatalog.find(p=>p.code==='QA-REGIONAL');
  ok(!!regionalProduct,'Regional manager can add a product');
  const regionalEdited=(await call(`admin/products/${regionalProduct.id}`,'PUT',{...regionalProduct,name:'Produs regional actualizat QA'},regional)).data.products.find(p=>p.id===regionalProduct.id);
  ok(regionalEdited?.name==='Produs regional actualizat QA','Regional manager can edit a product');
  await call(`admin/products/${regionalProduct.id}`,'DELETE',{version:regionalEdited.version},regional);
  ok(!(await call('admin/products','GET',null,regional)).data.products.some(p=>p.id===regionalProduct.id),'Regional manager can delete a product');
  await call('admin/products','POST',{...productBody,price:-1},manager,400);
  const catalogAfter=(await call('admin/products','POST',productBody,manager)).data.products;
  const custom=catalogAfter.find(p=>p.code==='QA-CUSTOM');
  ok(custom&&custom.sourceRow===0,'New product is persisted without assigning a template row');
  ok((await call('bootstrap','GET',null,agent)).data.products.some(p=>p.id===custom.id),'Agent receives new manager product');
  let customOrder=await create('stands',agent);
  customOrder=await save(customOrder,agent,{items:[{id:custom.id,quantity:123}]});
  const editedCatalog=(await call(`admin/products/${custom.id}`,'PUT',{...custom,name:'Produs actualizat QA',price:24.2,netPrice:20},manager)).data.products;
  const editedProduct=editedCatalog.find(p=>p.id===custom.id);
  await call(`admin/products/${custom.id}`,'PUT',custom,manager,409);
  await call(`orders/${customOrder.id}/finalize`,'POST',{revision:customOrder.revision},agent,409);
  customOrder=await save(customOrder,agent);
  customOrder=(await call(`orders/${customOrder.id}/finalize`,'POST',{revision:customOrder.revision},agent)).data.order;
  ok(customOrder.total===2976.6,'Updated catalog price owns finalized totals');
  const customBytes=new Uint8Array(await fetch(root+`orders/${customOrder.id}/excel`,{headers:{Cookie:agent}}).then(r=>r.arrayBuffer()));
  const customZip=unzipSync(customBytes);
  ok(strFromU8(customZip['xl/workbook.xml']).includes('Produse suplimentare'),'Custom products export in supplemental sheet');
  ok(Object.entries(customZip).some(([name,data])=>name.startsWith('xl/worksheets/')&&strFromU8(data).includes('QA-CUSTOM')&&strFromU8(data).includes('<v>123</v>')),'Supplemental export includes product and three-digit quantity');
  writeFileSync(folder+'/custom-products.xlsx',customBytes);
  let obsolete=await create('stands',agent);obsolete=await save(obsolete,agent,{items:[{id:custom.id,quantity:1}]});
  await call(`admin/products/${custom.id}`,'DELETE',{version:editedProduct.version},agent,403);
  await call(`admin/products/${custom.id}`,'DELETE',{version:editedProduct.version},manager);
  ok(!(await call('bootstrap','GET',null,agent)).data.products.some(p=>p.id===custom.id),'Deleted product removed from agent catalog');
  await call(`orders/${obsolete.id}/finalize`,'POST',{revision:obsolete.revision},agent,409);
  await call(`orders/${obsolete.id}`,'PUT',{revision:obsolete.revision,items:[{id:custom.id,quantity:1}]},agent,400);
  ok((await call(`orders/${customOrder.id}`,'GET',null,manager)).data.order.items[0].name==='Produs actualizat QA','Finalized product snapshot survives deletion');
  const restoredBytes=new Uint8Array(await fetch(root+`orders/${customOrder.id}/excel`,{headers:{Cookie:agent}}).then(r=>r.arrayBuffer()));
  ok(Buffer.from(restoredBytes).equals(Buffer.from(customBytes)),'Finalized export stays byte-identical after catalog deletion');
  const existingProduct=(await call('admin/products','GET',null,manager)).data.products.find(p=>p.id==='stand-2');
  const changedExisting=(await call(`admin/products/${existingProduct.id}`,'PUT',{...existingProduct,code:'QA-TEMPLATE',name:'Telefon editat QA',category:'Categoria QA mutată'},manager)).data.products.find(p=>p.id===existingProduct.id);
  ok(changedExisting.category==='Categoria QA mutată','Manager can move a product to another category');
  let templateOrder=await create('stands',agent);templateOrder=await save(templateOrder,agent,{items:[{id:existingProduct.id,quantity:222}]});
  templateOrder=(await call(`orders/${templateOrder.id}/finalize`,'POST',{revision:templateOrder.revision},agent)).data.order;
  const templateZip=unzipSync(new Uint8Array(await fetch(root+`orders/${templateOrder.id}/excel`,{headers:{Cookie:agent}}).then(r=>r.arrayBuffer())));
  ok(strFromU8(templateZip['xl/worksheets/sheet1.xml']).includes('QA-TEMPLATE')&&strFromU8(templateZip['xl/worksheets/sheet1.xml']).includes('Telefon editat QA'),'Edited template product code and name appear in original sheet');
  await call(`admin/products/${existingProduct.id}`,'PUT',{...existingProduct,version:changedExisting.version},manager);
  await call('auth/logout','POST',{},agent);await call('orders','GET',null,agent,401);
  let duplicateUsers=(await call('bootstrap','GET',null,manager)).data.users;
  let duplicateA=duplicateUsers.find(u=>u.id==='qa-agent1'),duplicateB=duplicateUsers.find(u=>u.id==='qa-agent2');
  duplicateA=(await call('admin/users/qa-agent1','PUT',{name:duplicateA.name,warehouseName:duplicateA.warehouseName,siteCode:'DUP-QA',version:duplicateA.profileVersion},manager)).data.users.find(u=>u.id==='qa-agent1');
  duplicateA=(await call('admin/users','POST',{action:'toggle',id:'qa-agent1',version:duplicateA.profileVersion},manager)).data.users.find(u=>u.id==='qa-agent1');
  duplicateB=(await call('admin/users/qa-agent2','PUT',{name:duplicateB.name,warehouseName:duplicateB.warehouseName,siteCode:'DUP-QA',version:duplicateB.profileVersion},manager)).data.users.find(u=>u.id==='qa-agent2');
  await call('admin/users','POST',{action:'toggle',id:'qa-agent1',version:duplicateA.profileVersion},manager,409);
  duplicateUsers=(await call('bootstrap','GET',null,manager)).data.users;
  ok(!duplicateUsers.find(u=>u.id==='qa-agent1').active&&duplicateUsers.find(u=>u.id==='qa-agent2').active,'Reactivation refuses an active duplicate SiteCode');
  duplicateB=(await call('admin/users/qa-agent2','PUT',{name:duplicateB.name,warehouseName:duplicateB.warehouseName,siteCode:'',version:duplicateB.profileVersion},manager)).data.users.find(u=>u.id==='qa-agent2');
  duplicateA=(await call('admin/users','POST',{action:'toggle',id:'qa-agent1',version:duplicateA.profileVersion},manager)).data.users.find(u=>u.id==='qa-agent1');
  await call('admin/users/qa-agent1','PUT',{name:duplicateA.name,warehouseName:duplicateA.warehouseName,siteCode:originalProfile.siteCode,version:duplicateA.profileVersion},manager);
  const manifest=await (await fetch('http://localhost:3000/manifest.webmanifest')).json();ok(manifest.display==='standalone'&&manifest.icons.some(i=>i.sizes==='192x192')&&manifest.icons.some(i=>i.sizes==='512x512'),'Install manifest has required icons');
  const serviceWorker=await (await fetch('http://localhost:3000/sw.js')).text();ok(serviceWorker.includes("addEventListener('push'")&&serviceWorker.includes("addEventListener('notificationclick'")&&serviceWorker.includes('showNotification'),'Service worker handles native push and notification clicks');
  for(const icon of manifest.icons){const r=await fetch('http://localhost:3000'+icon.src);ok(r.ok,`Icon available ${icon.src}`);}
  writeFileSync(folder+'/results.json',JSON.stringify({checks,orders:created,accessory:acc,stand,sim},null,2));
  console.log(`PASS: ${checks} API, authorization, export and PWA checks.`);
} finally {
  writeFileSync(folder+'/cleanup.sql',`DELETE FROM serials WHERE order_id IN (SELECT id FROM orders WHERE user_id IN ('qa-agent1','qa-agent2','qa-manager'));\nDELETE FROM orders WHERE user_id IN ('qa-agent1','qa-agent2','qa-manager');\nDELETE FROM customers WHERE id LIKE 'partner-%';\nDELETE FROM partner_requests WHERE agent_id IN ('qa-agent1','qa-agent2') OR confirmed_by IN ('qa-manager','qa-regional');\nDELETE FROM push_subscriptions WHERE user_id IN ('qa-manager','qa-regional');\nDELETE FROM sessions WHERE user_id IN ('qa-agent1','qa-agent2','qa-manager','qa-regional');\nDELETE FROM manager_agents WHERE manager_id='qa-regional' OR agent_id IN ('qa-agent1','qa-agent2');\nDELETE FROM settings WHERE key IN ('agent-mail:qa-agent1','agent-mail:qa-agent2') OR key IN (SELECT 'manager-mail:'||id FROM users WHERE username IN ('qa.regional.peer','qa.regional.other'));\nDELETE FROM users WHERE id IN ('qa-agent1','qa-agent2','qa-manager','qa-regional') OR username IN ('qa.regional.peer','qa.regional.other');\nDELETE FROM login_attempts WHERE key LIKE 'account:qa.%';\nDELETE FROM customers WHERE warehouse_id='g-3' AND json_extract(data,'$.name')='CLIENT QA';`);
}
